// src/engine/params.zig
// Auto-generated by `zig build tune`. Also hand-editable.
//
// Defines Params (i16 fields), ParamsF64 (f64 fields), and default_params.
// Both types share the same flat-array serialisation layout: each Score
// contributes 2 consecutive f64 entries [mg, eg], i16 fields contribute 1.
// Field order matches the struct declaration order below.

const std = @import("std");

const score_mod = @import("score.zig");
pub const Score = score_mod.Score(i16);
pub const ScoreF64 = score_mod.Score(f64);

// Layout (declaration order):
//   piece_values            [6]Score      ->  12
//   passed_pawn_bonus       [8]Score      ->  16
//   mobility_bonus          [4][28]Score  -> 224
//   bishop_pair .. tempo    17×Score      ->  34
//   king_proximity_passer   i16           ->   1
//   pst                     [6][64]Score  -> 768
//                                     total 1055
pub const PARAM_COUNT: usize = 1055;

// ==============================================================================
// Params — integer (i16) evaluation parameters used at search time
// ==============================================================================

pub const Params = struct {
    piece_values: [6]Score, // king (idx 5) is frozen at 20000/20000
    passed_pawn_bonus: [8]Score, // ranks 0 and 7 are frozen at 0/0
    mobility_bonus: [4][28]Score,
    bishop_pair: Score,
    rook_open_file: Score,
    rook_semi_open: Score,
    rook_on_seventh: Score,
    isolated_pawn: Score,
    doubled_pawn: Score,
    backward_pawn: Score,
    connected_pawn: Score,
    protected_passed_pawn: Score,
    blocked_passed_pawn: Score,
    rook_behind_passer: Score,
    free_passed_pawn: Score,
    knight_outpost_defended: Score,
    bishop_outpost_defended: Score,
    pawn_shield: Score,
    pawn_shield_missing: Score,
    tempo: Score,
    king_proximity_passer: i16,
    pst: [6][64]Score, // pawn rank-0/7 rows frozen at 0/0

    // Serialise to a flat f64 slice. Used to initialise the SPSA float vector
    // and to read back tuned values at checkpoint/output time.
    pub fn toFloats(self: *const Params, out: []f64) void {
        std.debug.assert(out.len >= PARAM_COUNT);
        var i: usize = 0;

        for (self.piece_values) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        for (self.passed_pawn_bonus) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                out[i] = @floatFromInt(self.mobility_bonus[pi][mi].midgame());
                i += 1;
                out[i] = @floatFromInt(self.mobility_bonus[pi][mi].endgame());
                i += 1;
            }
        }
        // 17 named Score scalars in declaration order
        for ([_]Score{
            self.bishop_pair,
            self.rook_open_file,
            self.rook_semi_open,
            self.rook_on_seventh,
            self.isolated_pawn,
            self.doubled_pawn,
            self.backward_pawn,
            self.connected_pawn,
            self.protected_passed_pawn,
            self.blocked_passed_pawn,
            self.rook_behind_passer,
            self.free_passed_pawn,
            self.knight_outpost_defended,
            self.bishop_outpost_defended,
            self.pawn_shield,
            self.pawn_shield_missing,
            self.tempo,
        }) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        out[i] = @floatFromInt(self.king_proximity_passer);
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                out[i] = @floatFromInt(self.pst[pi][sq].midgame());
                i += 1;
                out[i] = @floatFromInt(self.pst[pi][sq].endgame());
                i += 1;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
    }

    // Deserialise from f64 slice, rounding each value to nearest i16 (clamped).
    // Only called at checkpoint writes and final codegen — never during SPSA.
    pub fn fromFloats(floats: []const f64) Params {
        std.debug.assert(floats.len >= PARAM_COUNT);
        var p: Params = undefined;
        var i: usize = 0;

        for (0..6) |pi| {
            p.piece_values[pi] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
            i += 2;
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
            i += 2;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
                i += 2;
            }
        }
        p.bishop_pair = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_open_file = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_semi_open = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_on_seventh = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.isolated_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.doubled_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.backward_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.connected_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.protected_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.blocked_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_behind_passer = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.free_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.knight_outpost_defended = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.bishop_outpost_defended = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.pawn_shield = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.pawn_shield_missing = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.tempo = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.king_proximity_passer = clampI16(floats[i]);
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
                i += 2;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
        return p;
    }
};

// ==============================================================================
// ParamsF64 — floating-point mirror of Params, used exclusively in the SPSA
// hot loop so that gradient estimation never sees i16 quantisation noise.
// ==============================================================================

pub const ParamsF64 = struct {
    piece_values: [6]ScoreF64,
    passed_pawn_bonus: [8]ScoreF64,
    mobility_bonus: [4][28]ScoreF64,
    bishop_pair: ScoreF64,
    rook_open_file: ScoreF64,
    rook_semi_open: ScoreF64,
    rook_on_seventh: ScoreF64,
    isolated_pawn: ScoreF64,
    doubled_pawn: ScoreF64,
    backward_pawn: ScoreF64,
    connected_pawn: ScoreF64,
    protected_passed_pawn: ScoreF64,
    blocked_passed_pawn: ScoreF64,
    rook_behind_passer: ScoreF64,
    free_passed_pawn: ScoreF64,
    knight_outpost_defended: ScoreF64,
    bishop_outpost_defended: ScoreF64,
    pawn_shield: ScoreF64,
    pawn_shield_missing: ScoreF64,
    tempo: ScoreF64,
    king_proximity_passer: f64,
    pst: [6][64]ScoreF64,

    // Deserialise from f64 slice without rounding. Used in the SPSA hot loop.
    pub fn fromFloats(floats: []const f64) ParamsF64 {
        std.debug.assert(floats.len >= PARAM_COUNT);
        var p: ParamsF64 = undefined;
        var i: usize = 0;

        for (0..6) |pi| {
            p.piece_values[pi] = ScoreF64.init(floats[i], floats[i + 1]);
            i += 2;
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = ScoreF64.init(floats[i], floats[i + 1]);
            i += 2;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = ScoreF64.init(floats[i], floats[i + 1]);
                i += 2;
            }
        }
        p.bishop_pair = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_open_file = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_semi_open = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_on_seventh = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.isolated_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.doubled_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.backward_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.connected_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.protected_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.blocked_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_behind_passer = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.free_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.knight_outpost_defended = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.bishop_outpost_defended = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.pawn_shield = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.pawn_shield_missing = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.tempo = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.king_proximity_passer = floats[i];
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = ScoreF64.init(floats[i], floats[i + 1]);
                i += 2;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
        return p;
    }

    // Round each f64 field to nearest i16. Used to produce the final Params
    // for checkpoint writes and codegen output.
    pub fn toParams(self: *const ParamsF64) Params {
        var p: Params = undefined;

        for (0..6) |pi| {
            p.piece_values[pi] = Score.init(
                clampI16(self.piece_values[pi].midgame()),
                clampI16(self.piece_values[pi].endgame()),
            );
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = Score.init(
                clampI16(self.passed_pawn_bonus[ri].midgame()),
                clampI16(self.passed_pawn_bonus[ri].endgame()),
            );
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = Score.init(
                    clampI16(self.mobility_bonus[pi][mi].midgame()),
                    clampI16(self.mobility_bonus[pi][mi].endgame()),
                );
            }
        }
        p.bishop_pair = Score.init(clampI16(self.bishop_pair.midgame()), clampI16(self.bishop_pair.endgame()));
        p.rook_open_file = Score.init(clampI16(self.rook_open_file.midgame()), clampI16(self.rook_open_file.endgame()));
        p.rook_semi_open = Score.init(clampI16(self.rook_semi_open.midgame()), clampI16(self.rook_semi_open.endgame()));
        p.rook_on_seventh = Score.init(clampI16(self.rook_on_seventh.midgame()), clampI16(self.rook_on_seventh.endgame()));
        p.isolated_pawn = Score.init(clampI16(self.isolated_pawn.midgame()), clampI16(self.isolated_pawn.endgame()));
        p.doubled_pawn = Score.init(clampI16(self.doubled_pawn.midgame()), clampI16(self.doubled_pawn.endgame()));
        p.backward_pawn = Score.init(clampI16(self.backward_pawn.midgame()), clampI16(self.backward_pawn.endgame()));
        p.connected_pawn = Score.init(clampI16(self.connected_pawn.midgame()), clampI16(self.connected_pawn.endgame()));
        p.protected_passed_pawn = Score.init(
            clampI16(self.protected_passed_pawn.midgame()),
            clampI16(self.protected_passed_pawn.endgame()),
        );
        p.blocked_passed_pawn = Score.init(clampI16(self.blocked_passed_pawn.midgame()), clampI16(self.blocked_passed_pawn.endgame()));
        p.rook_behind_passer = Score.init(clampI16(self.rook_behind_passer.midgame()), clampI16(self.rook_behind_passer.endgame()));
        p.free_passed_pawn = Score.init(clampI16(self.free_passed_pawn.midgame()), clampI16(self.free_passed_pawn.endgame()));
        p.knight_outpost_defended = Score.init(
            clampI16(self.knight_outpost_defended.midgame()),
            clampI16(self.knight_outpost_defended.endgame()),
        );
        p.bishop_outpost_defended = Score.init(
            clampI16(self.bishop_outpost_defended.midgame()),
            clampI16(self.bishop_outpost_defended.endgame()),
        );
        p.pawn_shield = Score.init(clampI16(self.pawn_shield.midgame()), clampI16(self.pawn_shield.endgame()));
        p.pawn_shield_missing = Score.init(
            clampI16(self.pawn_shield_missing.midgame()),
            clampI16(self.pawn_shield_missing.endgame()),
        );
        p.tempo = Score.init(clampI16(self.tempo.midgame()), clampI16(self.tempo.endgame()));
        p.king_proximity_passer = clampI16(self.king_proximity_passer);
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = Score.init(
                    clampI16(self.pst[pi][sq].midgame()),
                    clampI16(self.pst[pi][sq].endgame()),
                );
            }
        }
        return p;
    }
};

// ==============================================================================
// Default parameters — verbatim copy of the constants in evaluation.zig.
// This is the starting point for tuning and the production fallback.
// ==============================================================================

pub const default_params: Params = .{
    .piece_values = .{
        Score.init(126, 208), // pawn
        Score.init(781, 854), // knight
        Score.init(825, 915), // bishop
        Score.init(1276, 1380), // rook
        Score.init(2538, 2682), // queen
        Score.init(20000, 20000), // king (frozen)
    },
    .passed_pawn_bonus = .{
        Score.init(0, 0), // rank 0 (frozen)
        Score.init(9, 28), // rank 1
        Score.init(15, 31), // rank 2
        Score.init(17, 39), // rank 3
        Score.init(64, 70), // rank 4
        Score.init(171, 177), // rank 5
        Score.init(277, 260), // rank 6
        Score.init(0, 0), // rank 7 (frozen)
    },
    .mobility_bonus = .{
        // Knights (max 8)
        .{
            Score.init(-62, -81),
            Score.init(-53, -56),
            Score.init(-12, -31),
            Score.init(-4, -16),
            Score.init(3, 5),
            Score.init(13, 11),
            Score.init(22, 17),
            Score.init(28, 20),
            Score.init(33, 25),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
        },
        // Bishops (max 13)
        .{
            Score.init(-48, -59),
            Score.init(-20, -23),
            Score.init(16, -3),
            Score.init(26, 13),
            Score.init(38, 24),
            Score.init(51, 42),
            Score.init(55, 54),
            Score.init(63, 57),
            Score.init(63, 65),
            Score.init(68, 73),
            Score.init(81, 78),
            Score.init(81, 86),
            Score.init(91, 88),
            Score.init(98, 97),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
        },
        // Rooks (max 14)
        .{
            Score.init(-60, -78),
            Score.init(-20, -17),
            Score.init(2, 23),
            Score.init(3, 39),
            Score.init(3, 70),
            Score.init(11, 99),
            Score.init(22, 103),
            Score.init(31, 121),
            Score.init(40, 134),
            Score.init(40, 139),
            Score.init(41, 158),
            Score.init(48, 164),
            Score.init(57, 168),
            Score.init(57, 169),
            Score.init(62, 172),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
        },
        // Queens (max 27)
        .{
            Score.init(-30, -48),
            Score.init(-12, -30),
            Score.init(-8, -7),
            Score.init(-9, 19),
            Score.init(20, 40),
            Score.init(23, 55),
            Score.init(23, 59),
            Score.init(35, 75),
            Score.init(38, 78),
            Score.init(53, 96),
            Score.init(64, 96),
            Score.init(65, 100),
            Score.init(65, 121),
            Score.init(66, 127),
            Score.init(67, 131),
            Score.init(67, 133),
            Score.init(72, 136),
            Score.init(72, 141),
            Score.init(77, 147),
            Score.init(79, 150),
            Score.init(93, 151),
            Score.init(108, 168),
            Score.init(108, 168),
            Score.init(108, 171),
            Score.init(110, 182),
            Score.init(114, 182),
            Score.init(114, 192),
            Score.init(116, 218),
        },
    },
    .bishop_pair = Score.init(30, 50),
    .rook_open_file = Score.init(48, 27),
    .rook_semi_open = Score.init(19, 7),
    .rook_on_seventh = Score.init(20, 40),
    .isolated_pawn = Score.init(-15, -20),
    .doubled_pawn = Score.init(-10, -20),
    .backward_pawn = Score.init(-9, -22),
    .connected_pawn = Score.init(7, 10),
    .protected_passed_pawn = Score.init(15, 30),
    .blocked_passed_pawn = Score.init(-10, -20),
    .rook_behind_passer = Score.init(16, 29),
    .free_passed_pawn = Score.init(8, 18),
    .knight_outpost_defended = Score.init(56, 34),
    .bishop_outpost_defended = Score.init(31, 23),
    .pawn_shield = Score.init(15, 0),
    .pawn_shield_missing = Score.init(-10, 0),
    .tempo = Score.init(28, 28),
    .king_proximity_passer = 8,
    .pst = .{
        // Pawns (rank 0 and 7 frozen at 0)
        .{
            Score.init(0, 0),    Score.init(0, 0),     Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),
            Score.init(3, -10),  Score.init(3, -6),    Score.init(10, 10),  Score.init(19, 0),   Score.init(16, 14),  Score.init(19, 7),   Score.init(7, -5),   Score.init(-5, -19),
            Score.init(-9, -10), Score.init(-15, -10), Score.init(11, -10), Score.init(15, 4),   Score.init(32, 4),   Score.init(22, 3),   Score.init(5, -6),   Score.init(-22, -4),
            Score.init(-4, 6),   Score.init(-23, -2),  Score.init(6, -8),   Score.init(20, -4),  Score.init(40, -13), Score.init(17, -12), Score.init(4, -10),  Score.init(-8, -9),
            Score.init(13, 10),  Score.init(0, 5),     Score.init(-13, 4),  Score.init(1, -5),   Score.init(11, -5),  Score.init(-2, -5),  Score.init(-13, 14), Score.init(5, 9),
            Score.init(5, 28),   Score.init(-12, 20),  Score.init(-7, 21),  Score.init(22, 28),  Score.init(-8, 30),  Score.init(-5, 7),   Score.init(-15, 6),  Score.init(-8, 13),
            Score.init(-7, 0),   Score.init(7, -11),   Score.init(-3, 12),  Score.init(-13, 21), Score.init(5, 25),   Score.init(-16, 19), Score.init(10, 4),   Score.init(-8, 7),
            Score.init(0, 0),    Score.init(0, 0),     Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),
        },
        // Knights
        .{
            Score.init(-175, -96),  Score.init(-92, -65), Score.init(-74, -49), Score.init(-73, -21), Score.init(-73, -21), Score.init(-74, -49), Score.init(-92, -65), Score.init(-175, -96),
            Score.init(-77, -67),   Score.init(-41, -54), Score.init(-27, -18), Score.init(-15, 8),   Score.init(-15, 8),   Score.init(-27, -18), Score.init(-41, -54), Score.init(-77, -67),
            Score.init(-61, -40),   Score.init(-17, -27), Score.init(6, -8),    Score.init(12, 29),   Score.init(12, 29),   Score.init(6, -8),    Score.init(-17, -27), Score.init(-61, -40),
            Score.init(-35, -35),   Score.init(8, -2),    Score.init(40, 13),   Score.init(49, 28),   Score.init(49, 28),   Score.init(40, 13),   Score.init(8, -2),    Score.init(-35, -35),
            Score.init(-34, -45),   Score.init(13, -16),  Score.init(44, 9),    Score.init(51, 39),   Score.init(51, 39),   Score.init(44, 9),    Score.init(13, -16),  Score.init(-34, -45),
            Score.init(-9, -51),    Score.init(22, -44),  Score.init(58, -16),  Score.init(53, 17),   Score.init(53, 17),   Score.init(58, -16),  Score.init(22, -44),  Score.init(-9, -51),
            Score.init(-67, -69),   Score.init(-27, -50), Score.init(4, -51),   Score.init(37, 12),   Score.init(37, 12),   Score.init(4, -51),   Score.init(-27, -50), Score.init(-67, -69),
            Score.init(-201, -100), Score.init(-83, -88), Score.init(-56, -56), Score.init(-26, -17), Score.init(-26, -17), Score.init(-56, -56), Score.init(-83, -88), Score.init(-201, -100),
        },
        // Bishops
        .{
            Score.init(-53, -57), Score.init(-5, -30),  Score.init(-8, -37),  Score.init(-23, -12), Score.init(-23, -12), Score.init(-8, -37),  Score.init(-5, -30),  Score.init(-53, -57),
            Score.init(-15, -37), Score.init(8, -13),   Score.init(19, -17),  Score.init(4, 1),     Score.init(4, 1),     Score.init(19, -17),  Score.init(8, -13),   Score.init(-15, -37),
            Score.init(-7, -16),  Score.init(21, -1),   Score.init(-5, -2),   Score.init(17, 10),   Score.init(17, 10),   Score.init(-5, -2),   Score.init(21, -1),   Score.init(-7, -16),
            Score.init(-5, -20),  Score.init(11, -6),   Score.init(25, 0),    Score.init(39, 17),   Score.init(39, 17),   Score.init(25, 0),    Score.init(11, -6),   Score.init(-5, -20),
            Score.init(-12, -17), Score.init(29, -1),   Score.init(22, -14),  Score.init(31, 15),   Score.init(31, 15),   Score.init(22, -14),  Score.init(29, -1),   Score.init(-12, -17),
            Score.init(-16, -30), Score.init(6, 6),     Score.init(1, 4),     Score.init(11, 6),    Score.init(11, 6),    Score.init(1, 4),     Score.init(6, 6),     Score.init(-16, -30),
            Score.init(-17, -31), Score.init(-14, -20), Score.init(5, -1),    Score.init(0, 1),     Score.init(0, 1),     Score.init(5, -1),    Score.init(-14, -20), Score.init(-17, -31),
            Score.init(-48, -46), Score.init(1, -42),   Score.init(-14, -37), Score.init(-23, -24), Score.init(-23, -24), Score.init(-14, -37), Score.init(1, -42),   Score.init(-48, -46),
        },
        // Rooks
        .{
            Score.init(-31, -9),  Score.init(-20, -13), Score.init(-14, -10), Score.init(-5, -9), Score.init(-5, -9), Score.init(-14, -10), Score.init(-20, -13), Score.init(-31, -9),
            Score.init(-21, -12), Score.init(-13, -9),  Score.init(-8, -1),   Score.init(6, -2),  Score.init(6, -2),  Score.init(-8, -1),   Score.init(-13, -9),  Score.init(-21, -12),
            Score.init(-25, 6),   Score.init(-11, -8),  Score.init(-1, -2),   Score.init(3, -6),  Score.init(3, -6),  Score.init(-1, -2),   Score.init(-11, -8),  Score.init(-25, 6),
            Score.init(-13, -6),  Score.init(-5, 1),    Score.init(-4, -9),   Score.init(-6, 7),  Score.init(-6, 7),  Score.init(-4, -9),   Score.init(-5, 1),    Score.init(-13, -6),
            Score.init(-27, -5),  Score.init(-15, 8),   Score.init(-4, 7),    Score.init(3, -6),  Score.init(3, -6),  Score.init(-4, 7),    Score.init(-15, 8),   Score.init(-27, -5),
            Score.init(-22, 6),   Score.init(-2, 1),    Score.init(6, -7),    Score.init(12, 10), Score.init(12, 10), Score.init(6, -7),    Score.init(-2, 1),    Score.init(-22, 6),
            Score.init(-2, 4),    Score.init(12, 5),    Score.init(16, 20),   Score.init(18, -5), Score.init(18, -5), Score.init(16, 20),   Score.init(12, 5),    Score.init(-2, 4),
            Score.init(-17, 18),  Score.init(-19, 0),   Score.init(-1, 19),   Score.init(9, 13),  Score.init(9, 13),  Score.init(-1, 19),   Score.init(-19, 0),   Score.init(-17, 18),
        },
        // Queens
        .{
            Score.init(3, -69),  Score.init(-5, -57), Score.init(-5, -47), Score.init(4, -26),  Score.init(4, -26),  Score.init(-5, -47), Score.init(-5, -57), Score.init(3, -69),
            Score.init(-3, -55), Score.init(5, -31),  Score.init(8, -22),  Score.init(12, -4),  Score.init(12, -4),  Score.init(8, -22),  Score.init(5, -31),  Score.init(-3, -55),
            Score.init(-3, -39), Score.init(6, -18),  Score.init(13, -9),  Score.init(7, 3),    Score.init(7, 3),    Score.init(13, -9),  Score.init(6, -18),  Score.init(-3, -39),
            Score.init(4, -23),  Score.init(5, -3),   Score.init(9, 13),   Score.init(8, 24),   Score.init(8, 24),   Score.init(9, 13),   Score.init(5, -3),   Score.init(4, -23),
            Score.init(0, -29),  Score.init(14, -6),  Score.init(12, 9),   Score.init(5, 21),   Score.init(5, 21),   Score.init(12, 9),   Score.init(14, -6),  Score.init(0, -29),
            Score.init(-4, -38), Score.init(10, -18), Score.init(6, -12),  Score.init(8, 1),    Score.init(8, 1),    Score.init(6, -12),  Score.init(10, -18), Score.init(-4, -38),
            Score.init(-5, -50), Score.init(6, -27),  Score.init(10, -24), Score.init(8, -8),   Score.init(8, -8),   Score.init(10, -24), Score.init(6, -27),  Score.init(-5, -50),
            Score.init(-2, -75), Score.init(-2, -52), Score.init(1, -43),  Score.init(-2, -36), Score.init(-2, -36), Score.init(1, -43),  Score.init(-2, -52), Score.init(-2, -75),
        },
        // Kings
        .{
            Score.init(271, 1),   Score.init(327, 45),  Score.init(271, 85),  Score.init(198, 76),  Score.init(198, 76),  Score.init(271, 85),  Score.init(327, 45),  Score.init(271, 1),
            Score.init(278, 53),  Score.init(303, 100), Score.init(234, 133), Score.init(179, 135), Score.init(179, 135), Score.init(234, 133), Score.init(303, 100), Score.init(278, 53),
            Score.init(195, 88),  Score.init(258, 130), Score.init(169, 169), Score.init(120, 175), Score.init(120, 175), Score.init(169, 169), Score.init(258, 130), Score.init(195, 88),
            Score.init(164, 103), Score.init(190, 156), Score.init(138, 172), Score.init(98, 172),  Score.init(98, 172),  Score.init(138, 172), Score.init(190, 156), Score.init(164, 103),
            Score.init(154, 96),  Score.init(179, 166), Score.init(105, 199), Score.init(70, 199),  Score.init(70, 199),  Score.init(105, 199), Score.init(179, 166), Score.init(154, 96),
            Score.init(123, 92),  Score.init(145, 172), Score.init(81, 184),  Score.init(31, 191),  Score.init(31, 191),  Score.init(81, 184),  Score.init(145, 172), Score.init(123, 92),
            Score.init(88, 47),   Score.init(120, 121), Score.init(65, 116),  Score.init(33, 131),  Score.init(33, 131),  Score.init(65, 116),  Score.init(120, 121), Score.init(88, 47),
            Score.init(59, 11),   Score.init(89, 59),   Score.init(45, 73),   Score.init(-1, 78),   Score.init(-1, 78),   Score.init(45, 73),   Score.init(89, 59),   Score.init(59, 11),
        },
    },
};

// ==============================================================================
// Internal helpers
// ==============================================================================

// Round a f64 to the nearest i16, clamping to [minInt(i16), maxInt(i16)].
fn clampI16(v: f64) i16 {
    const rounded = @round(v);
    const min: f64 = @floatFromInt(std.math.minInt(i16));
    const max: f64 = @floatFromInt(std.math.maxInt(i16));
    return @intFromFloat(std.math.clamp(rounded, min, max));
}

// ==============================================================================
// Tests
// ==============================================================================

test "params round-trip: toFloats then fromFloats recovers default_params exactly" {
    var buf: [PARAM_COUNT]f64 = undefined;
    default_params.toFloats(&buf);
    const recovered = Params.fromFloats(&buf);

    // Re-serialise the recovered params and compare buffers element by element.
    // Since default_params contains only integer-valued i16 fields, the round-
    // trip through f64 and back must be bit-exact.
    var buf2: [PARAM_COUNT]f64 = undefined;
    recovered.toFloats(&buf2);

    for (0..PARAM_COUNT) |i| {
        try std.testing.expectEqual(buf[i], buf2[i]);
    }
}

test "paramsf64 fromFloats/toParams round-trips default_params exactly" {
    var buf: [PARAM_COUNT]f64 = undefined;
    default_params.toFloats(&buf);

    const p_f64 = ParamsF64.fromFloats(&buf);
    const recovered = p_f64.toParams();

    var buf2: [PARAM_COUNT]f64 = undefined;
    recovered.toFloats(&buf2);

    for (0..PARAM_COUNT) |i| {
        try std.testing.expectEqual(buf[i], buf2[i]);
    }
}
