// src/engine/params.zig
// Auto-generated by `zig build tune`. Also hand-editable.
//
// Defines Params (i16 fields), ParamsF64 (f64 fields), and default_params.
// Both types share the same flat-array serialisation layout: each Score
// contributes 2 consecutive f64 entries [mg, eg], i16 fields contribute 1.
// Field order matches the struct declaration order below.

const std = @import("std");

const score_mod = @import("score.zig");
pub const Score = score_mod.Score(i16);
pub const ScoreF64 = score_mod.Score(f64);

// Layout (declaration order):
//   piece_values            [6]Score      ->  12
//   passed_pawn_bonus       [8]Score      ->  16
//   mobility_bonus          [4][28]Score  -> 224
//   bishop_pair .. tempo    17×Score      ->  34
//   king_proximity_passer   i16           ->   1
//   pst                     [6][64]Score  -> 768
//                                     total 1055
pub const PARAM_COUNT: usize = 1055;

// ==============================================================================
// Params — integer (i16) evaluation parameters used at search time
// ==============================================================================

pub const Params = struct {
    piece_values: [6]Score, // king (idx 5) is frozen at 20000/20000
    passed_pawn_bonus: [8]Score, // ranks 0 and 7 are frozen at 0/0
    mobility_bonus: [4][28]Score,
    bishop_pair: Score,
    rook_open_file: Score,
    rook_semi_open: Score,
    rook_on_seventh: Score,
    isolated_pawn: Score,
    doubled_pawn: Score,
    backward_pawn: Score,
    connected_pawn: Score,
    protected_passed_pawn: Score,
    blocked_passed_pawn: Score,
    rook_behind_passer: Score,
    free_passed_pawn: Score,
    knight_outpost_defended: Score,
    bishop_outpost_defended: Score,
    pawn_shield: Score,
    pawn_shield_missing: Score,
    tempo: Score,
    king_proximity_passer: i16,
    pst: [6][64]Score, // pawn rank-0/7 rows frozen at 0/0

    // Serialise to a flat f64 slice. Used to initialise the SPSA float vector
    // and to read back tuned values at checkpoint/output time.
    pub fn toFloats(self: *const Params, out: []f64) void {
        std.debug.assert(out.len >= PARAM_COUNT);
        var i: usize = 0;

        for (self.piece_values) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        for (self.passed_pawn_bonus) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                out[i] = @floatFromInt(self.mobility_bonus[pi][mi].midgame());
                i += 1;
                out[i] = @floatFromInt(self.mobility_bonus[pi][mi].endgame());
                i += 1;
            }
        }
        // 17 named Score scalars in declaration order
        for ([_]Score{
            self.bishop_pair,
            self.rook_open_file,
            self.rook_semi_open,
            self.rook_on_seventh,
            self.isolated_pawn,
            self.doubled_pawn,
            self.backward_pawn,
            self.connected_pawn,
            self.protected_passed_pawn,
            self.blocked_passed_pawn,
            self.rook_behind_passer,
            self.free_passed_pawn,
            self.knight_outpost_defended,
            self.bishop_outpost_defended,
            self.pawn_shield,
            self.pawn_shield_missing,
            self.tempo,
        }) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        out[i] = @floatFromInt(self.king_proximity_passer);
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                out[i] = @floatFromInt(self.pst[pi][sq].midgame());
                i += 1;
                out[i] = @floatFromInt(self.pst[pi][sq].endgame());
                i += 1;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
    }

    // Deserialise from f64 slice, rounding each value to nearest i16 (clamped).
    // Only called at checkpoint writes and final codegen — never during SPSA.
    pub fn fromFloats(floats: []const f64) Params {
        std.debug.assert(floats.len >= PARAM_COUNT);
        var p: Params = undefined;
        var i: usize = 0;

        for (0..6) |pi| {
            p.piece_values[pi] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
            i += 2;
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
            i += 2;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
                i += 2;
            }
        }
        p.bishop_pair = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_open_file = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_semi_open = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_on_seventh = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.isolated_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.doubled_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.backward_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.connected_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.protected_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.blocked_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_behind_passer = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.free_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.knight_outpost_defended = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.bishop_outpost_defended = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.pawn_shield = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.pawn_shield_missing = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.tempo = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.king_proximity_passer = clampI16(floats[i]);
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
                i += 2;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
        return p;
    }
};

// ==============================================================================
// ParamsF64 — floating-point mirror of Params, used exclusively in the SPSA
// hot loop so that gradient estimation never sees i16 quantisation noise.
// ==============================================================================

pub const ParamsF64 = struct {
    piece_values: [6]ScoreF64,
    passed_pawn_bonus: [8]ScoreF64,
    mobility_bonus: [4][28]ScoreF64,
    bishop_pair: ScoreF64,
    rook_open_file: ScoreF64,
    rook_semi_open: ScoreF64,
    rook_on_seventh: ScoreF64,
    isolated_pawn: ScoreF64,
    doubled_pawn: ScoreF64,
    backward_pawn: ScoreF64,
    connected_pawn: ScoreF64,
    protected_passed_pawn: ScoreF64,
    blocked_passed_pawn: ScoreF64,
    rook_behind_passer: ScoreF64,
    free_passed_pawn: ScoreF64,
    knight_outpost_defended: ScoreF64,
    bishop_outpost_defended: ScoreF64,
    pawn_shield: ScoreF64,
    pawn_shield_missing: ScoreF64,
    tempo: ScoreF64,
    king_proximity_passer: f64,
    pst: [6][64]ScoreF64,

    // Deserialise from f64 slice without rounding. Used in the SPSA hot loop.
    pub fn fromFloats(floats: []const f64) ParamsF64 {
        std.debug.assert(floats.len >= PARAM_COUNT);
        var p: ParamsF64 = undefined;
        var i: usize = 0;

        for (0..6) |pi| {
            p.piece_values[pi] = ScoreF64.init(floats[i], floats[i + 1]);
            i += 2;
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = ScoreF64.init(floats[i], floats[i + 1]);
            i += 2;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = ScoreF64.init(floats[i], floats[i + 1]);
                i += 2;
            }
        }
        p.bishop_pair = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_open_file = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_semi_open = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_on_seventh = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.isolated_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.doubled_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.backward_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.connected_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.protected_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.blocked_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_behind_passer = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.free_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.knight_outpost_defended = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.bishop_outpost_defended = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.pawn_shield = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.pawn_shield_missing = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.tempo = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.king_proximity_passer = floats[i];
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = ScoreF64.init(floats[i], floats[i + 1]);
                i += 2;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
        return p;
    }

    // Round each f64 field to nearest i16. Used to produce the final Params
    // for checkpoint writes and codegen output.
    pub fn toParams(self: *const ParamsF64) Params {
        var p: Params = undefined;

        for (0..6) |pi| {
            p.piece_values[pi] = Score.init(
                clampI16(self.piece_values[pi].midgame()),
                clampI16(self.piece_values[pi].endgame()),
            );
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = Score.init(
                clampI16(self.passed_pawn_bonus[ri].midgame()),
                clampI16(self.passed_pawn_bonus[ri].endgame()),
            );
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = Score.init(
                    clampI16(self.mobility_bonus[pi][mi].midgame()),
                    clampI16(self.mobility_bonus[pi][mi].endgame()),
                );
            }
        }
        p.bishop_pair = Score.init(clampI16(self.bishop_pair.midgame()), clampI16(self.bishop_pair.endgame()));
        p.rook_open_file = Score.init(clampI16(self.rook_open_file.midgame()), clampI16(self.rook_open_file.endgame()));
        p.rook_semi_open = Score.init(clampI16(self.rook_semi_open.midgame()), clampI16(self.rook_semi_open.endgame()));
        p.rook_on_seventh = Score.init(clampI16(self.rook_on_seventh.midgame()), clampI16(self.rook_on_seventh.endgame()));
        p.isolated_pawn = Score.init(clampI16(self.isolated_pawn.midgame()), clampI16(self.isolated_pawn.endgame()));
        p.doubled_pawn = Score.init(clampI16(self.doubled_pawn.midgame()), clampI16(self.doubled_pawn.endgame()));
        p.backward_pawn = Score.init(clampI16(self.backward_pawn.midgame()), clampI16(self.backward_pawn.endgame()));
        p.connected_pawn = Score.init(clampI16(self.connected_pawn.midgame()), clampI16(self.connected_pawn.endgame()));
        p.protected_passed_pawn = Score.init(
            clampI16(self.protected_passed_pawn.midgame()),
            clampI16(self.protected_passed_pawn.endgame()),
        );
        p.blocked_passed_pawn = Score.init(clampI16(self.blocked_passed_pawn.midgame()), clampI16(self.blocked_passed_pawn.endgame()));
        p.rook_behind_passer = Score.init(clampI16(self.rook_behind_passer.midgame()), clampI16(self.rook_behind_passer.endgame()));
        p.free_passed_pawn = Score.init(clampI16(self.free_passed_pawn.midgame()), clampI16(self.free_passed_pawn.endgame()));
        p.knight_outpost_defended = Score.init(
            clampI16(self.knight_outpost_defended.midgame()),
            clampI16(self.knight_outpost_defended.endgame()),
        );
        p.bishop_outpost_defended = Score.init(
            clampI16(self.bishop_outpost_defended.midgame()),
            clampI16(self.bishop_outpost_defended.endgame()),
        );
        p.pawn_shield = Score.init(clampI16(self.pawn_shield.midgame()), clampI16(self.pawn_shield.endgame()));
        p.pawn_shield_missing = Score.init(
            clampI16(self.pawn_shield_missing.midgame()),
            clampI16(self.pawn_shield_missing.endgame()),
        );
        p.tempo = Score.init(clampI16(self.tempo.midgame()), clampI16(self.tempo.endgame()));
        p.king_proximity_passer = clampI16(self.king_proximity_passer);
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = Score.init(
                    clampI16(self.pst[pi][sq].midgame()),
                    clampI16(self.pst[pi][sq].endgame()),
                );
            }
        }
        return p;
    }
};

// ==============================================================================
// Default parameters — verbatim copy of the constants in evaluation.zig.
// This is the starting point for tuning and the production fallback.
// ==============================================================================

pub const default_params: Params = .{
    .piece_values = .{
        Score.init(243, 220), // pawn
        Score.init(1192, 597), // knight
        Score.init(1155, 709), // bishop
        Score.init(1552, 1132), // rook
        Score.init(2884, 2580), // queen
        Score.init(20000, 20000), // king (frozen)
    },
    .passed_pawn_bonus = .{
        Score.init(0, 0), // rank 0 (frozen)
        Score.init(111, -169), // rank 1
        Score.init(74, -124), // rank 2
        Score.init(65, -50), // rank 3
        Score.init(109, 26), // rank 4
        Score.init(121, 165), // rank 5
        Score.init(204, 338), // rank 6
        Score.init(0, 0), // rank 7 (frozen)
    },
    .mobility_bonus = .{
        // Knights (max 8)
        .{
            Score.init(-146, -92),
            Score.init(-63, -72),
            Score.init(-35, 27),
            Score.init(-9, 38),
            Score.init(19, 43),
            Score.init(37, 73),
            Score.init(58, 64),
            Score.init(66, 69),
            Score.init(93, 26),
            Score.init(-46, 57),
            Score.init(260, -77),
            Score.init(47, 259),
            Score.init(-36, -168),
            Score.init(91, 139),
            Score.init(210, -95),
            Score.init(-4, -125),
            Score.init(78, -85),
            Score.init(-98, 75),
            Score.init(-180, 87),
            Score.init(-75, -152),
            Score.init(-40, -14),
            Score.init(33, -181),
            Score.init(194, 59),
            Score.init(215, -130),
            Score.init(-98, 91),
            Score.init(94, 25),
            Score.init(17, 149),
            Score.init(-9, 36),
        },
        // Bishops (max 13)
        .{
            Score.init(-66, -181),
            Score.init(-40, -64),
            Score.init(10, -107),
            Score.init(15, -36),
            Score.init(43, -11),
            Score.init(62, -1),
            Score.init(72, 23),
            Score.init(80, 23),
            Score.init(88, 38),
            Score.init(111, 18),
            Score.init(152, 14),
            Score.init(120, 0),
            Score.init(23, 101),
            Score.init(135, -8),
            Score.init(-104, -225),
            Score.init(98, -14),
            Score.init(128, 151),
            Score.init(80, 19),
            Score.init(50, 38),
            Score.init(300, -162),
            Score.init(-23, 100),
            Score.init(-73, -30),
            Score.init(-143, 37),
            Score.init(150, -38),
            Score.init(81, 251),
            Score.init(25, 68),
            Score.init(72, -8),
            Score.init(138, -296),
        },
        // Rooks (max 14)
        .{
            Score.init(-303, -17),
            Score.init(-44, 13),
            Score.init(-13, 90),
            Score.init(-10, 108),
            Score.init(-20, 134),
            Score.init(-4, 137),
            Score.init(-3, 151),
            Score.init(11, 154),
            Score.init(24, 156),
            Score.init(38, 172),
            Score.init(40, 179),
            Score.init(42, 191),
            Score.init(93, 185),
            Score.init(81, 197),
            Score.init(184, 145),
            Score.init(-80, 182),
            Score.init(-62, 32),
            Score.init(-71, -184),
            Score.init(-149, 315),
            Score.init(76, 156),
            Score.init(45, -79),
            Score.init(-167, 18),
            Score.init(10, 242),
            Score.init(12, -87),
            Score.init(-113, 86),
            Score.init(19, -31),
            Score.init(-111, 9),
            Score.init(228, -37),
        },
        // Queens (max 27)
        .{
            Score.init(-94, 39),
            Score.init(-70, -10),
            Score.init(-45, -157),
            Score.init(-33, 110),
            Score.init(3, -20),
            Score.init(15, 38),
            Score.init(28, 77),
            Score.init(36, 99),
            Score.init(36, 161),
            Score.init(52, 138),
            Score.init(47, 170),
            Score.init(72, 148),
            Score.init(55, 236),
            Score.init(57, 192),
            Score.init(74, 234),
            Score.init(228, 53),
            Score.init(185, 144),
            Score.init(148, 175),
            Score.init(131, 194),
            Score.init(13, 238),
            Score.init(188, 112),
            Score.init(140, 157),
            Score.init(46, 84),
            Score.init(208, 66),
            Score.init(187, 61),
            Score.init(-58, 215),
            Score.init(-21, 367),
            Score.init(133, 274),
        },
    },
    .bishop_pair = Score.init(80, 133),
    .rook_open_file = Score.init(106, -20),
    .rook_semi_open = Score.init(42, 27),
    .rook_on_seventh = Score.init(19, -14),
    .isolated_pawn = Score.init(-47, -6),
    .doubled_pawn = Score.init(-2, -52),
    .backward_pawn = Score.init(-22, -15),
    .connected_pawn = Score.init(18, 5),
    .protected_passed_pawn = Score.init(54, 20),
    .blocked_passed_pawn = Score.init(-121, -48),
    .rook_behind_passer = Score.init(56, -15),
    .free_passed_pawn = Score.init(-120, -2),
    .knight_outpost_defended = Score.init(57, 49),
    .bishop_outpost_defended = Score.init(74, -8),
    .pawn_shield = Score.init(-4, -15),
    .pawn_shield_missing = Score.init(-49, 19),
    .tempo = Score.init(73, 65),
    .king_proximity_passer = 38,
    .pst = .{
        // Pawns (rank 0 and 7 frozen at 0)
        .{
            Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0),
            Score.init(-47,3), Score.init(-25,-3), Score.init(-23,28), Score.init(3,40), Score.init(1,34), Score.init(76,23), Score.init(86,-13), Score.init(1,-27),
            Score.init(-30,-11), Score.init(-42,0), Score.init(11,-5), Score.init(8,14), Score.init(59,6), Score.init(23,19), Score.init(89,-18), Score.init(23,-22),
            Score.init(-44,-6), Score.init(-56,16), Score.init(-8,-13), Score.init(40,-27), Score.init(33,-19), Score.init(58,-15), Score.init(3,2), Score.init(-19,-15),
            Score.init(-4,31), Score.init(-20,33), Score.init(1,7), Score.init(39,-34), Score.init(66,-28), Score.init(41,-2), Score.init(1,25), Score.init(-14,13),
            Score.init(-28,89), Score.init(-42,104), Score.init(53,57), Score.init(23,10), Score.init(73,-12), Score.init(210,5), Score.init(17,39), Score.init(76,57),
            Score.init(-4,90), Score.init(-93,121), Score.init(11,64), Score.init(-85,14), Score.init(-50,0), Score.init(22,37), Score.init(153,-20), Score.init(-118,53),
            Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0),
        },
        // Knights
        .{
            Score.init(-216,-201), Score.init(-69,9), Score.init(-54,-39), Score.init(-83,57), Score.init(-33,-39), Score.init(-60,20), Score.init(-75,-9), Score.init(20,-27),
            Score.init(-26,-60), Score.init(-42,-30), Score.init(-45,-79), Score.init(-39,-11), Score.init(-24,-13), Score.init(-120,62), Score.init(-35,65), Score.init(-54,-45),
            Score.init(-82,-12), Score.init(-95,5), Score.init(-36,-20), Score.init(-20,30), Score.init(-11,53), Score.init(-37,-8), Score.init(5,-60), Score.init(-64,-76),
            Score.init(-37,-11), Score.init(-63,21), Score.init(-29,34), Score.init(-18,35), Score.init(-10,82), Score.init(21,11), Score.init(-58,20), Score.init(-65,15),
            Score.init(-53,-1), Score.init(-33,-7), Score.init(-36,1), Score.init(45,59), Score.init(-16,51), Score.init(-6,49), Score.init(-34,15), Score.init(106,-65),
            Score.init(-47,-130), Score.init(-102,-17), Score.init(-19,32), Score.init(58,-2), Score.init(21,46), Score.init(135,-4), Score.init(160,-78), Score.init(-210,85),
            Score.init(-209,-23), Score.init(-111,3), Score.init(107,-62), Score.init(0,-31), Score.init(31,-22), Score.init(208,-150), Score.init(20,-93), Score.init(-13,-157),
            Score.init(-372,-199), Score.init(-37,-120), Score.init(-69,-136), Score.init(-31,12), Score.init(58,-99), Score.init(-272,15), Score.init(-30,31), Score.init(-204,-219),
        },
        // Bishops
        .{
            Score.init(-12,-4), Score.init(15,-4), Score.init(7,-49), Score.init(7,-42), Score.init(-9,-13), Score.init(-41,0), Score.init(-75,26), Score.init(11,-43),
            Score.init(-48,-14), Score.init(54,-88), Score.init(18,-53), Score.init(-10,-36), Score.init(7,-35), Score.init(94,-72), Score.init(94,-52), Score.init(-19,-102),
            Score.init(7,-18), Score.init(26,-11), Score.init(32,-31), Score.init(-8,10), Score.init(25,-18), Score.init(38,-27), Score.init(20,-60), Score.init(8,-6),
            Score.init(20,-90), Score.init(-57,11), Score.init(-5,-12), Score.init(73,-54), Score.init(59,-28), Score.init(-24,-8), Score.init(32,-83), Score.init(-28,-11),
            Score.init(-128,40), Score.init(-36,-3), Score.init(2,-36), Score.init(6,24), Score.init(25,-16), Score.init(-21,-44), Score.init(0,-36), Score.init(-12,-35),
            Score.init(-73,-18), Score.init(4,-38), Score.init(60,3), Score.init(-84,12), Score.init(84,-73), Score.init(82,22), Score.init(-58,11), Score.init(61,-59),
            Score.init(-121,-28), Score.init(-84,31), Score.init(-110,-60), Score.init(-133,-101), Score.init(-104,-41), Score.init(-13,6), Score.init(-142,-17), Score.init(32,-100),
            Score.init(-123,-21), Score.init(150,-172), Score.init(-12,-96), Score.init(-31,-132), Score.init(-149,-27), Score.init(-12,-71), Score.init(-127,-163), Score.init(-125,-86),
        },
        // Rooks
        .{
            Score.init(-35,-30), Score.init(-28,-43), Score.init(-13,-45), Score.init(-10,-38), Score.init(14,-64), Score.init(13,-57), Score.init(1,-77), Score.init(44,-125),
            Score.init(-75,-25), Score.init(-20,-42), Score.init(-47,2), Score.init(-36,-22), Score.init(-27,-16), Score.init(-23,4), Score.init(-84,-22), Score.init(-112,-39),
            Score.init(-61,-36), Score.init(-58,-42), Score.init(-121,11), Score.init(-15,-27), Score.init(-16,-7), Score.init(-30,-6), Score.init(-49,-19), Score.init(21,-67),
            Score.init(-47,-8), Score.init(-191,31), Score.init(-129,22), Score.init(10,-32), Score.init(-20,-30), Score.init(-34,-18), Score.init(133,-70), Score.init(-75,-57),
            Score.init(-98,22), Score.init(-24,-16), Score.init(-23,22), Score.init(-71,11), Score.init(43,-46), Score.init(54,-37), Score.init(-29,-7), Score.init(100,-37),
            Score.init(-11,-4), Score.init(36,-14), Score.init(-57,5), Score.init(-59,17), Score.init(29,5), Score.init(141,-45), Score.init(70,-26), Score.init(153,-66),
            Score.init(-53,8), Score.init(-69,47), Score.init(18,26), Score.init(123,-10), Score.init(22,-14), Score.init(-23,31), Score.init(151,-29), Score.init(-138,48),
            Score.init(0,0), Score.init(48,-3), Score.init(-42,15), Score.init(128,-45), Score.init(5,-19), Score.init(171,-48), Score.init(-25,7), Score.init(25,-32),
        },
        // Queens
        .{
            Score.init(19,-101), Score.init(37,-322), Score.init(19,-167), Score.init(16,-133), Score.init(-9,-36), Score.init(-78,45), Score.init(-26,-40), Score.init(104,-162),
            Score.init(15,-122), Score.init(16,-114), Score.init(-5,-2), Score.init(12,-14), Score.init(32,-91), Score.init(36,-118), Score.init(11,-21), Score.init(63,-250),
            Score.init(-16,-114), Score.init(-4,-12), Score.init(-5,-25), Score.init(-21,44), Score.init(-53,128), Score.init(22,-54), Score.init(77,-54), Score.init(46,65),
            Score.init(-48,66), Score.init(-46,-11), Score.init(-10,-88), Score.init(-42,116), Score.init(12,-16), Score.init(2,-45), Score.init(-6,98), Score.init(56,-164),
            Score.init(30,-216), Score.init(-36,104), Score.init(-33,-35), Score.init(-53,164), Score.init(28,31), Score.init(97,5), Score.init(-48,158), Score.init(23,62),
            Score.init(-39,-96), Score.init(25,-100), Score.init(66,10), Score.init(64,44), Score.init(176,30), Score.init(106,-86), Score.init(178,-111), Score.init(166,-125),
            Score.init(21,-222), Score.init(-120,88), Score.init(0,-55), Score.init(-33,-86), Score.init(18,34), Score.init(87,153), Score.init(14,167), Score.init(155,-128),
            Score.init(38,-177), Score.init(51,-159), Score.init(36,-26), Score.init(-95,38), Score.init(108,-73), Score.init(-5,-44), Score.init(-172,-12), Score.init(36,-209),
        },
        // Kings
        .{
            Score.init(280,-128), Score.init(373,13), Score.init(315,35), Score.init(102,75), Score.init(314,3), Score.init(250,43), Score.init(429,-21), Score.init(382,-69),
            Score.init(235,19), Score.init(183,75), Score.init(204,93), Score.init(140,108), Score.init(149,112), Score.init(198,106), Score.init(366,59), Score.init(284,51),
            Score.init(188,-4), Score.init(257,79), Score.init(72,136), Score.init(-39,166), Score.init(-33,173), Score.init(-42,179), Score.init(202,107), Score.init(125,94),
            Score.init(0,56), Score.init(209,101), Score.init(81,140), Score.init(131,128), Score.init(-122,189), Score.init(-99,184), Score.init(47,143), Score.init(143,101),
            Score.init(256,79), Score.init(127,125), Score.init(146,117), Score.init(45,152), Score.init(212,128), Score.init(335,121), Score.init(188,135), Score.init(187,99),
            Score.init(215,121), Score.init(145,135), Score.init(88,119), Score.init(24,134), Score.init(-18,161), Score.init(8,188), Score.init(218,182), Score.init(161,140),
            Score.init(124,76), Score.init(79,146), Score.init(3,101), Score.init(-9,70), Score.init(-60,169), Score.init(169,213), Score.init(207,257), Score.init(92,93),
            Score.init(-48,43), Score.init(227,42), Score.init(7,44), Score.init(3,118), Score.init(-78,96), Score.init(38,187), Score.init(62,16), Score.init(139,-24),
        },
    },
};























// ==============================================================================
// Internal helpers
// ==============================================================================

// Round a f64 to the nearest i16, clamping to [minInt(i16), maxInt(i16)].
fn clampI16(v: f64) i16 {
    const rounded = @round(v);
    const min: f64 = @floatFromInt(std.math.minInt(i16));
    const max: f64 = @floatFromInt(std.math.maxInt(i16));
    return @intFromFloat(std.math.clamp(rounded, min, max));
}

// ==============================================================================
// Tests
// ==============================================================================

test "params round-trip: toFloats then fromFloats recovers default_params exactly" {
    var buf: [PARAM_COUNT]f64 = undefined;
    default_params.toFloats(&buf);
    const recovered = Params.fromFloats(&buf);

    // Re-serialise the recovered params and compare buffers element by element.
    // Since default_params contains only integer-valued i16 fields, the round-
    // trip through f64 and back must be bit-exact.
    var buf2: [PARAM_COUNT]f64 = undefined;
    recovered.toFloats(&buf2);

    for (0..PARAM_COUNT) |i| {
        try std.testing.expectEqual(buf[i], buf2[i]);
    }
}

test "paramsf64 fromFloats/toParams round-trips default_params exactly" {
    var buf: [PARAM_COUNT]f64 = undefined;
    default_params.toFloats(&buf);

    const p_f64 = ParamsF64.fromFloats(&buf);
    const recovered = p_f64.toParams();

    var buf2: [PARAM_COUNT]f64 = undefined;
    recovered.toFloats(&buf2);

    for (0..PARAM_COUNT) |i| {
        try std.testing.expectEqual(buf[i], buf2[i]);
    }
}
