// src/engine/params.zig
// Auto-generated by `zig build tune`. Also hand-editable.
//
// Defines Params (i16 fields), ParamsF64 (f64 fields), and default_params.
// Both types share the same flat-array serialisation layout: each Score
// contributes 2 consecutive f64 entries [mg, eg], i16 fields contribute 1.
// Field order matches the struct declaration order below.

const std = @import("std");

const score_mod = @import("score.zig");
pub const Score = score_mod.Score(i16);
pub const ScoreF64 = score_mod.Score(f64);

// Layout (declaration order):
//   piece_values            [6]Score      ->  12
//   passed_pawn_bonus       [8]Score      ->  16
//   mobility_bonus          [4][28]Score  -> 224
//   bishop_pair .. tempo    17×Score      ->  34
//   king_proximity_passer   i16           ->   1
//   pst                     [6][64]Score  -> 768
//                                     total 1055
pub const PARAM_COUNT: usize = 1055;

// ==============================================================================
// Params — integer (i16) evaluation parameters used at search time
// ==============================================================================

pub const Params = struct {
    piece_values: [6]Score, // king (idx 5) is frozen at 20000/20000
    passed_pawn_bonus: [8]Score, // ranks 0 and 7 are frozen at 0/0
    mobility_bonus: [4][28]Score,
    bishop_pair: Score,
    rook_open_file: Score,
    rook_semi_open: Score,
    rook_on_seventh: Score,
    isolated_pawn: Score,
    doubled_pawn: Score,
    backward_pawn: Score,
    connected_pawn: Score,
    protected_passed_pawn: Score,
    blocked_passed_pawn: Score,
    rook_behind_passer: Score,
    free_passed_pawn: Score,
    knight_outpost_defended: Score,
    bishop_outpost_defended: Score,
    pawn_shield: Score,
    pawn_shield_missing: Score,
    tempo: Score,
    king_proximity_passer: i16,
    pst: [6][64]Score, // pawn rank-0/7 rows frozen at 0/0

    // Serialise to a flat f64 slice. Used to initialise the SPSA float vector
    // and to read back tuned values at checkpoint/output time.
    pub fn toFloats(self: *const Params, out: []f64) void {
        std.debug.assert(out.len >= PARAM_COUNT);
        var i: usize = 0;

        for (self.piece_values) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        for (self.passed_pawn_bonus) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                out[i] = @floatFromInt(self.mobility_bonus[pi][mi].midgame());
                i += 1;
                out[i] = @floatFromInt(self.mobility_bonus[pi][mi].endgame());
                i += 1;
            }
        }
        // 17 named Score scalars in declaration order
        for ([_]Score{
            self.bishop_pair,
            self.rook_open_file,
            self.rook_semi_open,
            self.rook_on_seventh,
            self.isolated_pawn,
            self.doubled_pawn,
            self.backward_pawn,
            self.connected_pawn,
            self.protected_passed_pawn,
            self.blocked_passed_pawn,
            self.rook_behind_passer,
            self.free_passed_pawn,
            self.knight_outpost_defended,
            self.bishop_outpost_defended,
            self.pawn_shield,
            self.pawn_shield_missing,
            self.tempo,
        }) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        out[i] = @floatFromInt(self.king_proximity_passer);
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                out[i] = @floatFromInt(self.pst[pi][sq].midgame());
                i += 1;
                out[i] = @floatFromInt(self.pst[pi][sq].endgame());
                i += 1;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
    }

    // Deserialise from f64 slice, rounding each value to nearest i16 (clamped).
    // Only called at checkpoint writes and final codegen — never during SPSA.
    pub fn fromFloats(floats: []const f64) Params {
        std.debug.assert(floats.len >= PARAM_COUNT);
        var p: Params = undefined;
        var i: usize = 0;

        for (0..6) |pi| {
            p.piece_values[pi] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
            i += 2;
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
            i += 2;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
                i += 2;
            }
        }
        p.bishop_pair = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_open_file = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_semi_open = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_on_seventh = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.isolated_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.doubled_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.backward_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.connected_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.protected_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.blocked_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_behind_passer = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.free_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.knight_outpost_defended = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.bishop_outpost_defended = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.pawn_shield = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.pawn_shield_missing = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.tempo = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.king_proximity_passer = clampI16(floats[i]);
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
                i += 2;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
        return p;
    }
};

// ==============================================================================
// ParamsF64 — floating-point mirror of Params, used exclusively in the SPSA
// hot loop so that gradient estimation never sees i16 quantisation noise.
// ==============================================================================

pub const ParamsF64 = struct {
    piece_values: [6]ScoreF64,
    passed_pawn_bonus: [8]ScoreF64,
    mobility_bonus: [4][28]ScoreF64,
    bishop_pair: ScoreF64,
    rook_open_file: ScoreF64,
    rook_semi_open: ScoreF64,
    rook_on_seventh: ScoreF64,
    isolated_pawn: ScoreF64,
    doubled_pawn: ScoreF64,
    backward_pawn: ScoreF64,
    connected_pawn: ScoreF64,
    protected_passed_pawn: ScoreF64,
    blocked_passed_pawn: ScoreF64,
    rook_behind_passer: ScoreF64,
    free_passed_pawn: ScoreF64,
    knight_outpost_defended: ScoreF64,
    bishop_outpost_defended: ScoreF64,
    pawn_shield: ScoreF64,
    pawn_shield_missing: ScoreF64,
    tempo: ScoreF64,
    king_proximity_passer: f64,
    pst: [6][64]ScoreF64,

    // Deserialise from f64 slice without rounding. Used in the SPSA hot loop.
    pub fn fromFloats(floats: []const f64) ParamsF64 {
        std.debug.assert(floats.len >= PARAM_COUNT);
        var p: ParamsF64 = undefined;
        var i: usize = 0;

        for (0..6) |pi| {
            p.piece_values[pi] = ScoreF64.init(floats[i], floats[i + 1]);
            i += 2;
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = ScoreF64.init(floats[i], floats[i + 1]);
            i += 2;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = ScoreF64.init(floats[i], floats[i + 1]);
                i += 2;
            }
        }
        p.bishop_pair = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_open_file = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_semi_open = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_on_seventh = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.isolated_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.doubled_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.backward_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.connected_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.protected_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.blocked_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_behind_passer = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.free_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.knight_outpost_defended = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.bishop_outpost_defended = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.pawn_shield = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.pawn_shield_missing = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.tempo = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.king_proximity_passer = floats[i];
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = ScoreF64.init(floats[i], floats[i + 1]);
                i += 2;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
        return p;
    }

    // Round each f64 field to nearest i16. Used to produce the final Params
    // for checkpoint writes and codegen output.
    pub fn toParams(self: *const ParamsF64) Params {
        var p: Params = undefined;

        for (0..6) |pi| {
            p.piece_values[pi] = Score.init(
                clampI16(self.piece_values[pi].midgame()),
                clampI16(self.piece_values[pi].endgame()),
            );
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = Score.init(
                clampI16(self.passed_pawn_bonus[ri].midgame()),
                clampI16(self.passed_pawn_bonus[ri].endgame()),
            );
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = Score.init(
                    clampI16(self.mobility_bonus[pi][mi].midgame()),
                    clampI16(self.mobility_bonus[pi][mi].endgame()),
                );
            }
        }
        p.bishop_pair = Score.init(clampI16(self.bishop_pair.midgame()), clampI16(self.bishop_pair.endgame()));
        p.rook_open_file = Score.init(clampI16(self.rook_open_file.midgame()), clampI16(self.rook_open_file.endgame()));
        p.rook_semi_open = Score.init(clampI16(self.rook_semi_open.midgame()), clampI16(self.rook_semi_open.endgame()));
        p.rook_on_seventh = Score.init(clampI16(self.rook_on_seventh.midgame()), clampI16(self.rook_on_seventh.endgame()));
        p.isolated_pawn = Score.init(clampI16(self.isolated_pawn.midgame()), clampI16(self.isolated_pawn.endgame()));
        p.doubled_pawn = Score.init(clampI16(self.doubled_pawn.midgame()), clampI16(self.doubled_pawn.endgame()));
        p.backward_pawn = Score.init(clampI16(self.backward_pawn.midgame()), clampI16(self.backward_pawn.endgame()));
        p.connected_pawn = Score.init(clampI16(self.connected_pawn.midgame()), clampI16(self.connected_pawn.endgame()));
        p.protected_passed_pawn = Score.init(
            clampI16(self.protected_passed_pawn.midgame()),
            clampI16(self.protected_passed_pawn.endgame()),
        );
        p.blocked_passed_pawn = Score.init(clampI16(self.blocked_passed_pawn.midgame()), clampI16(self.blocked_passed_pawn.endgame()));
        p.rook_behind_passer = Score.init(clampI16(self.rook_behind_passer.midgame()), clampI16(self.rook_behind_passer.endgame()));
        p.free_passed_pawn = Score.init(clampI16(self.free_passed_pawn.midgame()), clampI16(self.free_passed_pawn.endgame()));
        p.knight_outpost_defended = Score.init(
            clampI16(self.knight_outpost_defended.midgame()),
            clampI16(self.knight_outpost_defended.endgame()),
        );
        p.bishop_outpost_defended = Score.init(
            clampI16(self.bishop_outpost_defended.midgame()),
            clampI16(self.bishop_outpost_defended.endgame()),
        );
        p.pawn_shield = Score.init(clampI16(self.pawn_shield.midgame()), clampI16(self.pawn_shield.endgame()));
        p.pawn_shield_missing = Score.init(
            clampI16(self.pawn_shield_missing.midgame()),
            clampI16(self.pawn_shield_missing.endgame()),
        );
        p.tempo = Score.init(clampI16(self.tempo.midgame()), clampI16(self.tempo.endgame()));
        p.king_proximity_passer = clampI16(self.king_proximity_passer);
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = Score.init(
                    clampI16(self.pst[pi][sq].midgame()),
                    clampI16(self.pst[pi][sq].endgame()),
                );
            }
        }
        return p;
    }
};

// ==============================================================================
// Default parameters — verbatim copy of the constants in evaluation.zig.
// This is the starting point for tuning and the production fallback.
// ==============================================================================

pub const default_params: Params = .{
    .piece_values = .{
        Score.init(248, 233), // pawn
        Score.init(1157, 612), // knight
        Score.init(1071, 666), // bishop
        Score.init(1462, 1122), // rook
        Score.init(2777, 2588), // queen
        Score.init(20000, 20000), // king (frozen)
    },
    .passed_pawn_bonus = .{
        Score.init(0, 0), // rank 0 (frozen)
        Score.init(58, -84), // rank 1
        Score.init(13, -35), // rank 2
        Score.init(2, 42), // rank 3
        Score.init(40, 126), // rank 4
        Score.init(34, 260), // rank 5
        Score.init(136, 436), // rank 6
        Score.init(0, 0), // rank 7 (frozen)
    },
    .mobility_bonus = .{
        // Knights (max 8)
        .{
            Score.init(-128, -102),
            Score.init(-86, -62),
            Score.init(-50, 18),
            Score.init(-22, 39),
            Score.init(3, 25),
            Score.init(17, 55),
            Score.init(38, 41),
            Score.init(50, 48),
            Score.init(57, 11),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
        },
        // Bishops (max 13)
        .{
            Score.init(-47, -33),
            Score.init(1, -82),
            Score.init(44, -71),
            Score.init(50, -13),
            Score.init(76, 14),
            Score.init(94, 27),
            Score.init(100, 53),
            Score.init(112, 59),
            Score.init(117, 72),
            Score.init(145, 37),
            Score.init(177, 32),
            Score.init(119, 38),
            Score.init(147, 52),
            Score.init(51, 60),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
        },
        // Rooks (max 14)
        .{
            Score.init(-110, 22),
            Score.init(-22, 36),
            Score.init(23, 39),
            Score.init(24, 57),
            Score.init(13, 96),
            Score.init(27, 106),
            Score.init(25, 116),
            Score.init(37, 131),
            Score.init(51, 138),
            Score.init(53, 147),
            Score.init(60, 161),
            Score.init(59, 174),
            Score.init(62, 194),
            Score.init(12, 200),
            Score.init(77, 157),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
            Score.init(0, 0),
        },
        // Queens (max 27)
        .{
            Score.init(-38, 28),
            Score.init(-11, -127),
            Score.init(-26, 59),
            Score.init(18, 19),
            Score.init(34, 8),
            Score.init(45, 65),
            Score.init(65, 17),
            Score.init(71, 30),
            Score.init(82, 35),
            Score.init(83, 89),
            Score.init(94, 48),
            Score.init(93, 115),
            Score.init(113, 96),
            Score.init(94, 129),
            Score.init(156, 100),
            Score.init(182, 23),
            Score.init(109, 150),
            Score.init(117, 149),
            Score.init(94, 143),
            Score.init(97, 137),
            Score.init(153, 119),
            Score.init(118, 130),
            Score.init(157, 197),
            Score.init(168, 113),
            Score.init(200, 110),
            Score.init(103, 228),
            Score.init(77, 60),
            Score.init(82, 183),
        },
    },
    .bishop_pair = Score.init(89, 116),
    .rook_open_file = Score.init(117, -21),
    .rook_semi_open = Score.init(48, 23),
    .rook_on_seventh = Score.init(-13, 16),
    .isolated_pawn = Score.init(-49, -2),
    .doubled_pawn = Score.init(0, -53),
    .backward_pawn = Score.init(-22, -17),
    .connected_pawn = Score.init(18, 9),
    .protected_passed_pawn = Score.init(56, 17),
    .blocked_passed_pawn = Score.init(-78, -138),
    .rook_behind_passer = Score.init(60, -4),
    .free_passed_pawn = Score.init(-61, -98),
    .knight_outpost_defended = Score.init(42, 50),
    .bishop_outpost_defended = Score.init(113, -25),
    .pawn_shield = Score.init(38, -16),
    .pawn_shield_missing = Score.init(-3, 17),
    .tempo = Score.init(70, 64),
    .king_proximity_passer = 39,
    .pst = .{
        // Pawns (rank 0 and 7 frozen at 0)
        .{
            Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0),
            Score.init(-63,-20), Score.init(-36,-9), Score.init(-30,8), Score.init(10,-38), Score.init(-13,23), Score.init(60,11), Score.init(73,-20), Score.init(6,-47),
            Score.init(-48,-29), Score.init(-49,-19), Score.init(3,-18), Score.init(-4,-10), Score.init(50,-15), Score.init(16,-2), Score.init(74,-26), Score.init(31,-47),
            Score.init(-55,-25), Score.init(-64,9), Score.init(-14,-29), Score.init(36,-48), Score.init(26,-31), Score.init(45,-29), Score.init(-3,-13), Score.init(-17,-29),
            Score.init(-13,3), Score.init(-11,1), Score.init(-6,-13), Score.init(33,-49), Score.init(61,-50), Score.init(57,-29), Score.init(-26,15), Score.init(42,-38),
            Score.init(19,30), Score.init(-5,64), Score.init(30,59), Score.init(63,-44), Score.init(49,-23), Score.init(76,8), Score.init(23,66), Score.init(74,35),
            Score.init(11,9), Score.init(51,11), Score.init(28,17), Score.init(-41,37), Score.init(-9,24), Score.init(9,-1), Score.init(4,2), Score.init(-36,18),
            Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0), Score.init(0,0),
        },
        // Knights
        .{
            Score.init(-242,-174), Score.init(-38,-81), Score.init(-94,-123), Score.init(-30,-29), Score.init(-20,-44), Score.init(-28,-48), Score.init(-37,-110), Score.init(-123,-148),
            Score.init(-149,-30), Score.init(-105,-33), Score.init(3,-78), Score.init(-13,-7), Score.init(-7,-41), Score.init(26,26), Score.init(-32,-19), Score.init(-27,-107),
            Score.init(-86,22), Score.init(-76,5), Score.init(-8,-20), Score.init(-1,26), Score.init(-11,47), Score.init(-16,-14), Score.init(-14,-33), Score.init(-53,-8),
            Score.init(4,-58), Score.init(-10,64), Score.init(-10,40), Score.init(-27,124), Score.init(18,78), Score.init(46,-16), Score.init(-35,40), Score.init(-42,17),
            Score.init(-49,82), Score.init(-5,-11), Score.init(-1,19), Score.init(96,20), Score.init(2,70), Score.init(33,26), Score.init(-29,49), Score.init(1,-12),
            Score.init(-116,-38), Score.init(-20,-17), Score.init(40,-83), Score.init(81,71), Score.init(81,29), Score.init(160,56), Score.init(7,-99), Score.init(-59,-76),
            Score.init(-127,-35), Score.init(-21,-48), Score.init(99,-80), Score.init(67,-97), Score.init(-9,-44), Score.init(29,-105), Score.init(-80,-22), Score.init(-39,-48),
            Score.init(-116,-83), Score.init(-52,-184), Score.init(-36,-50), Score.init(-35,23), Score.init(11,-7), Score.init(-195,46), Score.init(-31,-35), Score.init(-172,-70),
        },
        // Bishops
        .{
            Score.init(-72,-48), Score.init(-55,-80), Score.init(16,-15), Score.init(0,-13), Score.init(20,24), Score.init(-28,23), Score.init(31,-35), Score.init(-11,-59),
            Score.init(16,-98), Score.init(57,-43), Score.init(23,-3), Score.init(7,-3), Score.init(18,-1), Score.init(31,28), Score.init(102,-21), Score.init(37,-153),
            Score.init(-5,1), Score.init(66,-48), Score.init(77,-24), Score.init(10,5), Score.init(50,-29), Score.init(36,20), Score.init(49,-37), Score.init(55,-32),
            Score.init(20,-27), Score.init(-2,-93), Score.init(4,19), Score.init(60,-14), Score.init(29,75), Score.init(0,25), Score.init(10,12), Score.init(3,-120),
            Score.init(-55,55), Score.init(-16,-52), Score.init(-3,10), Score.init(66,1), Score.init(60,-41), Score.init(-11,-16), Score.init(14,-21), Score.init(30,-133),
            Score.init(-30,-55), Score.init(-80,-6), Score.init(27,-10), Score.init(41,-58), Score.init(89,73), Score.init(18,34), Score.init(17,3), Score.init(34,-46),
            Score.init(-42,-40), Score.init(-58,-48), Score.init(-110,-4), Score.init(-22,-72), Score.init(38,15), Score.init(36,15), Score.init(-16,-57), Score.init(-4,-19),
            Score.init(-20,-29), Score.init(-83,-105), Score.init(21,-112), Score.init(-47,27), Score.init(-133,-24), Score.init(-133,4), Score.init(105,-71), Score.init(-106,-52),
        },
        // Rooks
        .{
            Score.init(-19,-6), Score.init(-18,4), Score.init(2,-12), Score.init(10,-23), Score.init(26,-39), Score.init(15,-6), Score.init(-43,-24), Score.init(-12,-43),
            Score.init(5,-79), Score.init(-88,-12), Score.init(3,-46), Score.init(48,-53), Score.init(-2,38), Score.init(20,-26), Score.init(70,45), Score.init(-22,-85),
            Score.init(-31,-7), Score.init(8,-58), Score.init(-44,30), Score.init(-26,48), Score.init(-19,-7), Score.init(14,-76), Score.init(-13,51), Score.init(11,-24),
            Score.init(-104,-1), Score.init(34,-17), Score.init(-86,29), Score.init(102,-60), Score.init(-28,-12), Score.init(-32,30), Score.init(-27,-44), Score.init(-64,-7),
            Score.init(-36,17), Score.init(-79,-11), Score.init(29,12), Score.init(21,0), Score.init(31,11), Score.init(-79,13), Score.init(-13,-5), Score.init(-36,-24),
            Score.init(-59,52), Score.init(-49,7), Score.init(-35,25), Score.init(45,-26), Score.init(53,-13), Score.init(-24,-41), Score.init(7,-2), Score.init(-94,50),
            Score.init(58,-9), Score.init(23,1), Score.init(71,0), Score.init(-7,16), Score.init(5,8), Score.init(-60,-6), Score.init(5,9), Score.init(-119,105),
            Score.init(49,40), Score.init(-72,-12), Score.init(-75,-10), Score.init(30,23), Score.init(124,-11), Score.init(-42,-31), Score.init(-15,21), Score.init(46,73),
        },
        // Queens
        .{
            Score.init(28,-190), Score.init(9,-90), Score.init(-6,-15), Score.init(12,-78), Score.init(-8,-157), Score.init(-15,-101), Score.init(95,-123), Score.init(41,-227),
            Score.init(48,-79), Score.init(35,-122), Score.init(21,-96), Score.init(31,-34), Score.init(29,-56), Score.init(55,-116), Score.init(15,-21), Score.init(21,-12),
            Score.init(29,-129), Score.init(9,-53), Score.init(56,-65), Score.init(1,-50), Score.init(21,-51), Score.init(-9,30), Score.init(87,20), Score.init(4,74),
            Score.init(-5,-151), Score.init(-92,110), Score.init(-21,-73), Score.init(-20,15), Score.init(22,-32), Score.init(24,-22), Score.init(13,-58), Score.init(-23,-7),
            Score.init(-96,-9), Score.init(-7,-34), Score.init(24,-66), Score.init(6,19), Score.init(-15,70), Score.init(54,20), Score.init(64,-19), Score.init(9,66),
            Score.init(-24,-66), Score.init(12,-102), Score.init(34,54), Score.init(31,74), Score.init(22,-19), Score.init(40,67), Score.init(55,-33), Score.init(59,64),
            Score.init(31,-81), Score.init(-78,-84), Score.init(-71,109), Score.init(34,-71), Score.init(71,-58), Score.init(28,4), Score.init(18,-37), Score.init(-16,44),
            Score.init(19,-101), Score.init(24,-117), Score.init(44,-44), Score.init(-73,-6), Score.init(22,-33), Score.init(24,27), Score.init(64,-53), Score.init(1,33),
        },
        // Kings
        .{
            Score.init(202,-27), Score.init(375,-26), Score.init(339,7), Score.init(175,13), Score.init(322,2), Score.init(245,47), Score.init(388,-2), Score.init(378,-63),
            Score.init(272,22), Score.init(254,97), Score.init(209,100), Score.init(212,85), Score.init(175,96), Score.init(188,116), Score.init(309,86), Score.init(320,42),
            Score.init(84,108), Score.init(222,90), Score.init(229,135), Score.init(121,154), Score.init(126,151), Score.init(209,156), Score.init(321,119), Score.init(170,120),
            Score.init(208,77), Score.init(115,116), Score.init(61,160), Score.init(140,181), Score.init(93,165), Score.init(150,164), Score.init(231,103), Score.init(266,135),
            Score.init(123,96), Score.init(90,154), Score.init(186,111), Score.init(117,156), Score.init(78,162), Score.init(135,136), Score.init(172,141), Score.init(71,140),
            Score.init(236,41), Score.init(218,134), Score.init(6,138), Score.init(27,147), Score.init(75,150), Score.init(21,147), Score.init(195,83), Score.init(252,121),
            Score.init(82,31), Score.init(64,155), Score.init(169,165), Score.init(-6,158), Score.init(94,180), Score.init(87,141), Score.init(150,126), Score.init(118,58),
            Score.init(69,111), Score.init(128,48), Score.init(-16,60), Score.init(1,59), Score.init(-15,142), Score.init(-24,66), Score.init(51,93), Score.init(81,66),
        },
    },
};















// ==============================================================================
// Internal helpers
// ==============================================================================

// Round a f64 to the nearest i16, clamping to [minInt(i16), maxInt(i16)].
fn clampI16(v: f64) i16 {
    const rounded = @round(v);
    const min: f64 = @floatFromInt(std.math.minInt(i16));
    const max: f64 = @floatFromInt(std.math.maxInt(i16));
    return @intFromFloat(std.math.clamp(rounded, min, max));
}

// ==============================================================================
// Tests
// ==============================================================================

test "params round-trip: toFloats then fromFloats recovers default_params exactly" {
    var buf: [PARAM_COUNT]f64 = undefined;
    default_params.toFloats(&buf);
    const recovered = Params.fromFloats(&buf);

    // Re-serialise the recovered params and compare buffers element by element.
    // Since default_params contains only integer-valued i16 fields, the round-
    // trip through f64 and back must be bit-exact.
    var buf2: [PARAM_COUNT]f64 = undefined;
    recovered.toFloats(&buf2);

    for (0..PARAM_COUNT) |i| {
        try std.testing.expectEqual(buf[i], buf2[i]);
    }
}

test "paramsf64 fromFloats/toParams round-trips default_params exactly" {
    var buf: [PARAM_COUNT]f64 = undefined;
    default_params.toFloats(&buf);

    const p_f64 = ParamsF64.fromFloats(&buf);
    const recovered = p_f64.toParams();

    var buf2: [PARAM_COUNT]f64 = undefined;
    recovered.toFloats(&buf2);

    for (0..PARAM_COUNT) |i| {
        try std.testing.expectEqual(buf[i], buf2[i]);
    }
}
