// src/engine/params.zig
// Auto-generated by `zig build tune`. Also hand-editable.
//
// Defines Params (i16 fields), ParamsF64 (f64 fields), and default_params.
// Both types share the same flat-array serialisation layout: each Score
// contributes 2 consecutive f64 entries [mg, eg], i16 fields contribute 1.
// Field order matches the struct declaration order below.

const std = @import("std");

const score_mod = @import("score.zig");
pub const Score = score_mod.Score(i16);
pub const ScoreF64 = score_mod.Score(f64);

// Layout (declaration order):
//   piece_values            [6]Score      ->  12
//   passed_pawn_bonus       [8]Score      ->  16
//   mobility_bonus          [4][28]Score  -> 224
//   bishop_pair .. tempo    17×Score      ->  34
//   king_proximity_passer   i16           ->   1
//   pst                     [6][64]Score  -> 768
//                                     total 1055
pub const PARAM_COUNT: usize = 1055;

// ==============================================================================
// Params — integer (i16) evaluation parameters used at search time
// ==============================================================================

pub const Params = struct {
    piece_values: [6]Score, // king (idx 5) is frozen at 20000/20000
    passed_pawn_bonus: [8]Score, // ranks 0 and 7 are frozen at 0/0
    mobility_bonus: [4][28]Score,
    bishop_pair: Score,
    rook_open_file: Score,
    rook_semi_open: Score,
    rook_on_seventh: Score,
    isolated_pawn: Score,
    doubled_pawn: Score,
    backward_pawn: Score,
    connected_pawn: Score,
    protected_passed_pawn: Score,
    blocked_passed_pawn: Score,
    rook_behind_passer: Score,
    free_passed_pawn: Score,
    knight_outpost_defended: Score,
    bishop_outpost_defended: Score,
    pawn_shield: Score,
    pawn_shield_missing: Score,
    tempo: Score,
    king_proximity_passer: i16,
    pst: [6][64]Score, // pawn rank-0/7 rows frozen at 0/0

    // Serialise to a flat f64 slice. Used to initialise the SPSA float vector
    // and to read back tuned values at checkpoint/output time.
    pub fn toFloats(self: *const Params, out: []f64) void {
        std.debug.assert(out.len >= PARAM_COUNT);
        var i: usize = 0;

        for (self.piece_values) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        for (self.passed_pawn_bonus) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                out[i] = @floatFromInt(self.mobility_bonus[pi][mi].midgame());
                i += 1;
                out[i] = @floatFromInt(self.mobility_bonus[pi][mi].endgame());
                i += 1;
            }
        }
        // 17 named Score scalars in declaration order
        for ([_]Score{
            self.bishop_pair,
            self.rook_open_file,
            self.rook_semi_open,
            self.rook_on_seventh,
            self.isolated_pawn,
            self.doubled_pawn,
            self.backward_pawn,
            self.connected_pawn,
            self.protected_passed_pawn,
            self.blocked_passed_pawn,
            self.rook_behind_passer,
            self.free_passed_pawn,
            self.knight_outpost_defended,
            self.bishop_outpost_defended,
            self.pawn_shield,
            self.pawn_shield_missing,
            self.tempo,
        }) |s| {
            out[i] = @floatFromInt(s.midgame());
            i += 1;
            out[i] = @floatFromInt(s.endgame());
            i += 1;
        }
        out[i] = @floatFromInt(self.king_proximity_passer);
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                out[i] = @floatFromInt(self.pst[pi][sq].midgame());
                i += 1;
                out[i] = @floatFromInt(self.pst[pi][sq].endgame());
                i += 1;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
    }

    // Deserialise from f64 slice, rounding each value to nearest i16 (clamped).
    // Only called at checkpoint writes and final codegen — never during SPSA.
    pub fn fromFloats(floats: []const f64) Params {
        std.debug.assert(floats.len >= PARAM_COUNT);
        var p: Params = undefined;
        var i: usize = 0;

        for (0..6) |pi| {
            p.piece_values[pi] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
            i += 2;
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
            i += 2;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
                i += 2;
            }
        }
        p.bishop_pair = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_open_file = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_semi_open = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_on_seventh = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.isolated_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.doubled_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.backward_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.connected_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.protected_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.blocked_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.rook_behind_passer = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.free_passed_pawn = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.knight_outpost_defended = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.bishop_outpost_defended = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.pawn_shield = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.pawn_shield_missing = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.tempo = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
        i += 2;
        p.king_proximity_passer = clampI16(floats[i]);
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = Score.init(clampI16(floats[i]), clampI16(floats[i + 1]));
                i += 2;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
        return p;
    }
};

// ==============================================================================
// ParamsF64 — floating-point mirror of Params, used exclusively in the SPSA
// hot loop so that gradient estimation never sees i16 quantisation noise.
// ==============================================================================

pub const ParamsF64 = struct {
    piece_values: [6]ScoreF64,
    passed_pawn_bonus: [8]ScoreF64,
    mobility_bonus: [4][28]ScoreF64,
    bishop_pair: ScoreF64,
    rook_open_file: ScoreF64,
    rook_semi_open: ScoreF64,
    rook_on_seventh: ScoreF64,
    isolated_pawn: ScoreF64,
    doubled_pawn: ScoreF64,
    backward_pawn: ScoreF64,
    connected_pawn: ScoreF64,
    protected_passed_pawn: ScoreF64,
    blocked_passed_pawn: ScoreF64,
    rook_behind_passer: ScoreF64,
    free_passed_pawn: ScoreF64,
    knight_outpost_defended: ScoreF64,
    bishop_outpost_defended: ScoreF64,
    pawn_shield: ScoreF64,
    pawn_shield_missing: ScoreF64,
    tempo: ScoreF64,
    king_proximity_passer: f64,
    pst: [6][64]ScoreF64,

    // Deserialise from f64 slice without rounding. Used in the SPSA hot loop.
    pub fn fromFloats(floats: []const f64) ParamsF64 {
        std.debug.assert(floats.len >= PARAM_COUNT);
        var p: ParamsF64 = undefined;
        var i: usize = 0;

        for (0..6) |pi| {
            p.piece_values[pi] = ScoreF64.init(floats[i], floats[i + 1]);
            i += 2;
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = ScoreF64.init(floats[i], floats[i + 1]);
            i += 2;
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = ScoreF64.init(floats[i], floats[i + 1]);
                i += 2;
            }
        }
        p.bishop_pair = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_open_file = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_semi_open = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_on_seventh = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.isolated_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.doubled_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.backward_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.connected_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.protected_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.blocked_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.rook_behind_passer = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.free_passed_pawn = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.knight_outpost_defended = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.bishop_outpost_defended = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.pawn_shield = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.pawn_shield_missing = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.tempo = ScoreF64.init(floats[i], floats[i + 1]);
        i += 2;
        p.king_proximity_passer = floats[i];
        i += 1;
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = ScoreF64.init(floats[i], floats[i + 1]);
                i += 2;
            }
        }
        std.debug.assert(i == PARAM_COUNT);
        return p;
    }

    // Round each f64 field to nearest i16. Used to produce the final Params
    // for checkpoint writes and codegen output.
    pub fn toParams(self: *const ParamsF64) Params {
        var p: Params = undefined;

        for (0..6) |pi| {
            p.piece_values[pi] = Score.init(
                clampI16(self.piece_values[pi].midgame()),
                clampI16(self.piece_values[pi].endgame()),
            );
        }
        for (0..8) |ri| {
            p.passed_pawn_bonus[ri] = Score.init(
                clampI16(self.passed_pawn_bonus[ri].midgame()),
                clampI16(self.passed_pawn_bonus[ri].endgame()),
            );
        }
        for (0..4) |pi| {
            for (0..28) |mi| {
                p.mobility_bonus[pi][mi] = Score.init(
                    clampI16(self.mobility_bonus[pi][mi].midgame()),
                    clampI16(self.mobility_bonus[pi][mi].endgame()),
                );
            }
        }
        p.bishop_pair = Score.init(clampI16(self.bishop_pair.midgame()), clampI16(self.bishop_pair.endgame()));
        p.rook_open_file = Score.init(clampI16(self.rook_open_file.midgame()), clampI16(self.rook_open_file.endgame()));
        p.rook_semi_open = Score.init(clampI16(self.rook_semi_open.midgame()), clampI16(self.rook_semi_open.endgame()));
        p.rook_on_seventh = Score.init(clampI16(self.rook_on_seventh.midgame()), clampI16(self.rook_on_seventh.endgame()));
        p.isolated_pawn = Score.init(clampI16(self.isolated_pawn.midgame()), clampI16(self.isolated_pawn.endgame()));
        p.doubled_pawn = Score.init(clampI16(self.doubled_pawn.midgame()), clampI16(self.doubled_pawn.endgame()));
        p.backward_pawn = Score.init(clampI16(self.backward_pawn.midgame()), clampI16(self.backward_pawn.endgame()));
        p.connected_pawn = Score.init(clampI16(self.connected_pawn.midgame()), clampI16(self.connected_pawn.endgame()));
        p.protected_passed_pawn = Score.init(
            clampI16(self.protected_passed_pawn.midgame()),
            clampI16(self.protected_passed_pawn.endgame()),
        );
        p.blocked_passed_pawn = Score.init(clampI16(self.blocked_passed_pawn.midgame()), clampI16(self.blocked_passed_pawn.endgame()));
        p.rook_behind_passer = Score.init(clampI16(self.rook_behind_passer.midgame()), clampI16(self.rook_behind_passer.endgame()));
        p.free_passed_pawn = Score.init(clampI16(self.free_passed_pawn.midgame()), clampI16(self.free_passed_pawn.endgame()));
        p.knight_outpost_defended = Score.init(
            clampI16(self.knight_outpost_defended.midgame()),
            clampI16(self.knight_outpost_defended.endgame()),
        );
        p.bishop_outpost_defended = Score.init(
            clampI16(self.bishop_outpost_defended.midgame()),
            clampI16(self.bishop_outpost_defended.endgame()),
        );
        p.pawn_shield = Score.init(clampI16(self.pawn_shield.midgame()), clampI16(self.pawn_shield.endgame()));
        p.pawn_shield_missing = Score.init(
            clampI16(self.pawn_shield_missing.midgame()),
            clampI16(self.pawn_shield_missing.endgame()),
        );
        p.tempo = Score.init(clampI16(self.tempo.midgame()), clampI16(self.tempo.endgame()));
        p.king_proximity_passer = clampI16(self.king_proximity_passer);
        for (0..6) |pi| {
            for (0..64) |sq| {
                p.pst[pi][sq] = Score.init(
                    clampI16(self.pst[pi][sq].midgame()),
                    clampI16(self.pst[pi][sq].endgame()),
                );
            }
        }
        return p;
    }
};

// ==============================================================================
// Default parameters — verbatim copy of the constants in evaluation.zig.
// This is the starting point for tuning and the production fallback.
// ==============================================================================

pub const default_params: Params = .{
    .piece_values = .{
        Score.init(197, 244), // pawn
        Score.init(878, 810), // knight
        Score.init(832, 824), // bishop
        Score.init(1201, 1333), // rook
        Score.init(2576, 2696), // queen
        Score.init(20000, 20000), // king (frozen)
    },
    .passed_pawn_bonus = .{
        Score.init(0, 0), // rank 0 (frozen)
        Score.init(4, -71), // rank 1
        Score.init(12, -60), // rank 2
        Score.init(-14, 16), // rank 3
        Score.init(45, 85), // rank 4
        Score.init(156, 228), // rank 5
        Score.init(286, 388), // rank 6
        Score.init(0, 0), // rank 7 (frozen)
    },
    .mobility_bonus = .{
        // Knights (max 8)
        .{
            Score.init(-91, -85),
            Score.init(-46, -78),
            Score.init(-21, -22),
            Score.init(-6, -7),
            Score.init(18, 2),
            Score.init(26, 28),
            Score.init(41, 26),
            Score.init(42, 37),
            Score.init(54, 22),
            Score.init(-22, 30),
            Score.init(14, 1),
            Score.init(-14, 25),
            Score.init(1, 4),
            Score.init(20, 21),
            Score.init(-14, 7),
            Score.init(-4, -34),
            Score.init(-5, -8),
            Score.init(-10, 11),
            Score.init(-12, -40),
            Score.init(-4, -29),
            Score.init(-27, 21),
            Score.init(-18, 9),
            Score.init(5, -11),
            Score.init(32, 0),
            Score.init(-19, -10),
            Score.init(13, -38),
            Score.init(-1, -19),
            Score.init(-14, 3),
        },
        // Bishops (max 13)
        .{
            Score.init(-58, -60),
            Score.init(-18, -32),
            Score.init(17, -6),
            Score.init(31, 17),
            Score.init(53, 38),
            Score.init(71, 46),
            Score.init(78, 61),
            Score.init(87, 62),
            Score.init(85, 69),
            Score.init(73, 72),
            Score.init(89, 72),
            Score.init(93, 53),
            Score.init(82, 77),
            Score.init(90, 105),
            Score.init(4, -14),
            Score.init(-8, -35),
            Score.init(-3, -25),
            Score.init(4, 38),
            Score.init(20, -5),
            Score.init(-25, -22),
            Score.init(10, -9),
            Score.init(-36, -10),
            Score.init(-7, -34),
            Score.init(-19, 13),
            Score.init(18, 0),
            Score.init(9, 8),
            Score.init(7, -23),
            Score.init(6, 12),
        },
        // Rooks (max 14)
        .{
            Score.init(-59, -76),
            Score.init(-34, -28),
            Score.init(-10, 18),
            Score.init(-7, 26),
            Score.init(-10, 72),
            Score.init(-2, 108),
            Score.init(4, 114),
            Score.init(20, 118),
            Score.init(34, 136),
            Score.init(45, 143),
            Score.init(56, 151),
            Score.init(53, 173),
            Score.init(56, 172),
            Score.init(62, 163),
            Score.init(73, 161),
            Score.init(-7, 5),
            Score.init(6, -12),
            Score.init(-33, -12),
            Score.init(-9, -16),
            Score.init(5, 23),
            Score.init(10, -1),
            Score.init(-22, -1),
            Score.init(7, 22),
            Score.init(-11, 22),
            Score.init(8, -20),
            Score.init(6, -24),
            Score.init(8, 5),
            Score.init(0, -9),
        },
        // Queens (max 27)
        .{
            Score.init(-24, -39),
            Score.init(0, -65),
            Score.init(-12, 4),
            Score.init(-1, 29),
            Score.init(6, 51),
            Score.init(24, 64),
            Score.init(37, 75),
            Score.init(47, 63),
            Score.init(60, 69),
            Score.init(67, 101),
            Score.init(73, 69),
            Score.init(74, 123),
            Score.init(92, 139),
            Score.init(82, 152),
            Score.init(74, 128),
            Score.init(76, 129),
            Score.init(92, 131),
            Score.init(76, 140),
            Score.init(67, 151),
            Score.init(95, 131),
            Score.init(89, 128),
            Score.init(92, 160),
            Score.init(106, 181),
            Score.init(109, 164),
            Score.init(130, 184),
            Score.init(106, 151),
            Score.init(99, 200),
            Score.init(99, 184),
        },
    },
    .bishop_pair = Score.init(89, 84),
    .rook_open_file = Score.init(101, -1),
    .rook_semi_open = Score.init(48, 30),
    .rook_on_seventh = Score.init(9, 39),
    .isolated_pawn = Score.init(-46, -21),
    .doubled_pawn = Score.init(15, -35),
    .backward_pawn = Score.init(-23, -22),
    .connected_pawn = Score.init(21, 7),
    .protected_passed_pawn = Score.init(19, 7),
    .blocked_passed_pawn = Score.init(-31, -86),
    .rook_behind_passer = Score.init(32, 17),
    .free_passed_pawn = Score.init(-35, -28),
    .knight_outpost_defended = Score.init(57, 14),
    .bishop_outpost_defended = Score.init(61, 14),
    .pawn_shield = Score.init(28, -18),
    .pawn_shield_missing = Score.init(-8, 6),
    .tempo = Score.init(49, 47),
    .king_proximity_passer = 32,
    .pst = .{
        // Pawns (rank 0 and 7 frozen at 0)
        .{
            Score.init(0, 0),     Score.init(0, 0),     Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),     Score.init(0, 0),
            Score.init(-27, -22), Score.init(-28, -21), Score.init(-39, 7),  Score.init(-2, -10), Score.init(-9, 18),  Score.init(44, 3),   Score.init(46, -26),  Score.init(-17, -38),
            Score.init(-3, -41),  Score.init(-35, -12), Score.init(3, -23),  Score.init(3, -1),   Score.init(40, -5),  Score.init(21, -7),  Score.init(50, -31),  Score.init(9, -30),
            Score.init(-13, -18), Score.init(-47, -7),  Score.init(2, -24),  Score.init(35, -30), Score.init(55, -36), Score.init(36, -29), Score.init(-17, -12), Score.init(-15, -20),
            Score.init(9, 9),     Score.init(2, 8),     Score.init(-4, -9),  Score.init(46, -29), Score.init(47, -16), Score.init(19, -12), Score.init(1, 1),     Score.init(-3, 7),
            Score.init(12, 49),   Score.init(-4, 44),   Score.init(-3, 37),  Score.init(33, -4),  Score.init(-19, 12), Score.init(10, 26),  Score.init(-16, 47),  Score.init(-3, 39),
            Score.init(-6, 15),   Score.init(25, 22),   Score.init(-18, 13), Score.init(19, 32),  Score.init(42, 15),  Score.init(-20, 19), Score.init(-12, 26),  Score.init(-3, 43),
            Score.init(0, 0),     Score.init(0, 0),     Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),    Score.init(0, 0),     Score.init(0, 0),
        },
        // Knights
        .{
            Score.init(-170, -140), Score.init(-53, -79), Score.init(-75, -71), Score.init(-58, -37), Score.init(-42, -27), Score.init(-104, -53), Score.init(-50, -71),  Score.init(-196, -75),
            Score.init(-88, -51),   Score.init(-66, -39), Score.init(-37, -39), Score.init(-18, 1),   Score.init(-12, -5),  Score.init(-17, -36),  Score.init(-41, -58),  Score.init(-55, -38),
            Score.init(-94, -38),   Score.init(-40, -26), Score.init(-4, -18),  Score.init(10, 28),   Score.init(4, 23),    Score.init(14, -8),    Score.init(-4, -24),   Score.init(-54, -39),
            Score.init(-35, -23),   Score.init(-5, -5),   Score.init(31, 6),    Score.init(24, 47),   Score.init(44, 20),   Score.init(37, 26),    Score.init(-1, -3),    Score.init(-31, -14),
            Score.init(-54, -27),   Score.init(-14, -25), Score.init(63, 8),    Score.init(64, 52),   Score.init(48, 42),   Score.init(64, 21),    Score.init(26, 10),    Score.init(-33, -33),
            Score.init(13, -54),    Score.init(19, -60),  Score.init(53, -17),  Score.init(79, 16),   Score.init(83, 26),   Score.init(73, -2),    Score.init(37, -47),   Score.init(27, -26),
            Score.init(-64, -67),   Score.init(-35, -42), Score.init(17, -54),  Score.init(52, 6),    Score.init(8, -16),   Score.init(22, -68),   Score.init(-7, -21),   Score.init(-80, -76),
            Score.init(-200, -150), Score.init(-63, -94), Score.init(-39, -64), Score.init(-29, -46), Score.init(-17, -53), Score.init(-84, -64),  Score.init(-104, -48), Score.init(-258, -105),
        },
        // Bishops
        .{
            Score.init(-67, -61), Score.init(-19, -14), Score.init(0, -28),   Score.init(-22, -19), Score.init(-6, 14),  Score.init(-12, -19), Score.init(25, -32),  Score.init(-63, -39),
            Score.init(-10, -49), Score.init(24, -29),  Score.init(27, -39),  Score.init(8, -16),   Score.init(14, -11), Score.init(37, -22),  Score.init(80, -34),  Score.init(-16, -58),
            Score.init(-34, 1),   Score.init(32, -9),   Score.init(29, 2),    Score.init(17, 10),   Score.init(31, 26),  Score.init(28, 9),    Score.init(27, -7),   Score.init(3, -17),
            Score.init(29, -4),   Score.init(-7, -1),   Score.init(14, 13),   Score.init(72, 22),   Score.init(58, 37),  Score.init(13, 1),    Score.init(6, -30),   Score.init(-3, -31),
            Score.init(-22, -42), Score.init(-6, 1),    Score.init(-12, -22), Score.init(36, 23),   Score.init(20, 7),   Score.init(10, 1),    Score.init(17, -2),   Score.init(-12, -11),
            Score.init(11, -26),  Score.init(-28, -11), Score.init(6, 10),    Score.init(43, 14),   Score.init(0, 19),   Score.init(22, 5),    Score.init(12, -26),  Score.init(-11, -27),
            Score.init(-26, -17), Score.init(16, -32),  Score.init(-24, 6),   Score.init(18, -23),  Score.init(15, -12), Score.init(49, 3),    Score.init(-19, -25), Score.init(-29, -50),
            Score.init(-65, -41), Score.init(-3, -26),  Score.init(-17, -30), Score.init(-24, -38), Score.init(-4, -42), Score.init(0, -33),   Score.init(9, -64),   Score.init(-49, -46),
        },
        // Rooks
        .{
            Score.init(-17, -18), Score.init(-13, -17), Score.init(-17, 8),   Score.init(4, -1),   Score.init(13, -15), Score.init(10, 3),   Score.init(-49, -12), Score.init(-15, -31),
            Score.init(-10, -44), Score.init(-8, -26),  Score.init(-24, -15), Score.init(-1, -5),  Score.init(-16, -2), Score.init(-18, 13), Score.init(10, -4),   Score.init(-66, -34),
            Score.init(-47, 30),  Score.init(9, -9),    Score.init(-12, -2),  Score.init(-14, -8), Score.init(32, 9),   Score.init(-20, 1),  Score.init(-12, -20), Score.init(-54, -11),
            Score.init(-42, -10), Score.init(-17, -26), Score.init(-8, -6),   Score.init(-9, -16), Score.init(-1, 3),   Score.init(5, -17),  Score.init(1, -17),   Score.init(-8, -8),
            Score.init(-47, 7),   Score.init(-40, -5),  Score.init(11, 13),   Score.init(-19, 11), Score.init(27, -17), Score.init(-15, 25), Score.init(-31, -8),  Score.init(-21, 25),
            Score.init(-13, 13),  Score.init(-1, 7),    Score.init(-8, -12),  Score.init(29, 18),  Score.init(4, -5),   Score.init(18, -15), Score.init(-10, 8),   Score.init(-22, -2),
            Score.init(9, -3),    Score.init(22, 1),    Score.init(6, -6),    Score.init(18, -12), Score.init(1, -19),  Score.init(11, 14),  Score.init(13, 18),   Score.init(2, 6),
            Score.init(-19, 32),  Score.init(8, 14),    Score.init(-3, 19),   Score.init(24, 1),   Score.init(5, 8),    Score.init(0, 48),   Score.init(10, 14),   Score.init(-33, 33),
        },
        // Queens
        .{
            Score.init(25, -84),  Score.init(-32, -70), Score.init(5, -38),   Score.init(29, -45),  Score.init(-14, -36), Score.init(-32, -50), Score.init(4, -51),  Score.init(17, -96),
            Score.init(3, -67),   Score.init(4, -50),   Score.init(17, -33),  Score.init(17, -42),  Score.init(22, -13),  Score.init(23, -43),  Score.init(17, -64), Score.init(7, -47),
            Score.init(-35, -45), Score.init(-5, -15),  Score.init(6, -12),   Score.init(-5, 7),    Score.init(19, -8),   Score.init(41, -19),  Score.init(13, -8),  Score.init(19, -7),
            Score.init(3, -37),   Score.init(-5, -10),  Score.init(14, -7),   Score.init(-5, 21),   Score.init(-12, 16),  Score.init(18, 24),   Score.init(9, 1),    Score.init(-1, -40),
            Score.init(-32, -70), Score.init(-30, -22), Score.init(19, 10),   Score.init(4, 15),    Score.init(-2, 36),   Score.init(11, 27),   Score.init(32, 9),   Score.init(-5, -11),
            Score.init(-33, -51), Score.init(19, 0),    Score.init(-5, 4),    Score.init(13, 11),   Score.init(-1, -4),   Score.init(-21, 20),  Score.init(18, -25), Score.init(-13, -18),
            Score.init(7, -45),   Score.init(-16, -40), Score.init(10, -42),  Score.init(36, -11),  Score.init(17, 16),   Score.init(23, 9),    Score.init(24, -37), Score.init(13, -30),
            Score.init(-19, -89), Score.init(0, -38),   Score.init(-24, -53), Score.init(-37, -27), Score.init(14, -32),  Score.init(-22, -62), Score.init(-8, -17), Score.init(0, -38),
        },
        // Kings
        .{
            Score.init(269, 26),  Score.init(338, 43),  Score.init(296, 61),  Score.init(200, 67),  Score.init(277, 61),  Score.init(230, 71),  Score.init(352, 26),  Score.init(284, 0),
            Score.init(291, 28),  Score.init(295, 94),  Score.init(246, 130), Score.init(168, 134), Score.init(157, 139), Score.init(208, 124), Score.init(311, 95),  Score.init(283, 67),
            Score.init(193, 99),  Score.init(257, 154), Score.init(185, 160), Score.init(113, 172), Score.init(121, 184), Score.init(170, 159), Score.init(272, 135), Score.init(187, 89),
            Score.init(176, 118), Score.init(195, 142), Score.init(125, 178), Score.init(105, 177), Score.init(99, 175),  Score.init(146, 180), Score.init(207, 168), Score.init(162, 99),
            Score.init(152, 79),  Score.init(176, 158), Score.init(127, 184), Score.init(69, 201),  Score.init(63, 190),  Score.init(126, 189), Score.init(178, 167), Score.init(163, 86),
            Score.init(130, 89),  Score.init(148, 163), Score.init(83, 177),  Score.init(28, 208),  Score.init(29, 169),  Score.init(63, 180),  Score.init(146, 194), Score.init(137, 106),
            Score.init(109, 12),  Score.init(113, 112), Score.init(64, 103),  Score.init(7, 128),   Score.init(32, 139),  Score.init(63, 130),  Score.init(112, 110), Score.init(84, 56),
            Score.init(71, 3),    Score.init(95, 79),   Score.init(38, 83),   Score.init(8, 51),    Score.init(-30, 67),  Score.init(28, 75),   Score.init(75, 78),   Score.init(64, 33),
        },
    },
};

// ==============================================================================
// Internal helpers
// ==============================================================================

// Round a f64 to the nearest i16, clamping to [minInt(i16), maxInt(i16)].
fn clampI16(v: f64) i16 {
    const rounded = @round(v);
    const min: f64 = @floatFromInt(std.math.minInt(i16));
    const max: f64 = @floatFromInt(std.math.maxInt(i16));
    return @intFromFloat(std.math.clamp(rounded, min, max));
}

// ==============================================================================
// Tests
// ==============================================================================

test "params round-trip: toFloats then fromFloats recovers default_params exactly" {
    var buf: [PARAM_COUNT]f64 = undefined;
    default_params.toFloats(&buf);
    const recovered = Params.fromFloats(&buf);

    // Re-serialise the recovered params and compare buffers element by element.
    // Since default_params contains only integer-valued i16 fields, the round-
    // trip through f64 and back must be bit-exact.
    var buf2: [PARAM_COUNT]f64 = undefined;
    recovered.toFloats(&buf2);

    for (0..PARAM_COUNT) |i| {
        try std.testing.expectEqual(buf[i], buf2[i]);
    }
}

test "paramsf64 fromFloats/toParams round-trips default_params exactly" {
    var buf: [PARAM_COUNT]f64 = undefined;
    default_params.toFloats(&buf);

    const p_f64 = ParamsF64.fromFloats(&buf);
    const recovered = p_f64.toParams();

    var buf2: [PARAM_COUNT]f64 = undefined;
    recovered.toFloats(&buf2);

    for (0..PARAM_COUNT) |i| {
        try std.testing.expectEqual(buf[i], buf2[i]);
    }
}
